import { Injectable } from '@angular/core';
import { Strength } from '../models/Strength';
import { NoLimitationsNoted } from '../models/NoLimitationsNoted';
import { SelectiveTissueTensionUpper } from '../models/SelectiveTissueTensionUpper';
import { SelectiveTissueTensionLower } from '../models/SelectiveTissueTensionLower';
import { GripPinch } from '../models/GripPinch';
import { GrossMuscleTestsUpper } from '../models/GrossMuscleTestsUpper';
import { RedcordNeuracStabilityTests } from '../models/RedcordNeuracStabilityTests';
import { GrossMuscleTestsTrunk } from '../models/GrossMuscleTestsTrunk';
import { GrossMuscleTestsLower } from '../models/GrossMuscleTestsLower';
import { CoreStrength } from '../models/CoreStrength';
import { ManualMuscleTests } from '../models/ManualMuscleTests';
import { AdditionalComments } from '../models/AdditionalComments';

@Injectable({
  providedIn: 'root'
})
export class StrengthMapperService {

  constructor() { }

  /**
   * Converts DTO to form values
   * @param dto Strength DTO
   * @returns Form values object
   */
  fromDto(dto: Strength): any {
    return {
      // No Limitations Noted
      no_limitations_noted: dto.noLimitationsNoted?.noLimitationsNoted ? 'yes' : 'no',
      uper_extremity: dto.noLimitationsNoted?.uperExtremity || false,
      lower_extremity: dto.noLimitationsNoted?.lowerExtremity || false,

      // Selective Tissue Tension Upper
      selective_tissue_tension_upper: dto.selectiveTissueTensionUpper?.selectiveTissueTensionUpper ? 'yes' : 'no',
      cervical: dto.selectiveTissueTensionUpper?.cervical ? 'yes' : 'no',
      trunk: dto.selectiveTissueTensionUpper?.trunk ? 'yes' : 'no',
      back_ribs: dto.selectiveTissueTensionUpper?.backRibs ? 'yes' : 'no',
      shoulder: dto.selectiveTissueTensionUpper?.shoulder ? 'yes' : 'no',
      elbow: dto.selectiveTissueTensionUpper?.elbow ? 'yes' : 'no',
      wrist: dto.selectiveTissueTensionUpper?.wrist ? 'yes' : 'no',
      hand: dto.selectiveTissueTensionUpper?.hand ? 'yes' : 'no',

      // Selective Tissue Tension Lower
      selective_tissue_tension_lower: dto.selectiveTissueTensionLower?.selectiveTissueTensionLower ? 'yes' : 'no',
      hip: dto.selectiveTissueTensionLower?.hip ? 'yes' : 'no',
      knee: dto.selectiveTissueTensionLower?.knee ? 'yes' : 'no',
      ankle: dto.selectiveTissueTensionLower?.ankle ? 'yes' : 'no',
      foot: dto.selectiveTissueTensionLower?.foot ? 'yes' : 'no',

      // Grip Pinch
      grip_pinch: dto.gripPinch?.gripPinch ? 'yes' : 'no',
      grip_pinch_power_grip_right: dto.gripPinch?.gripPinchPowerGripRight || '',
      grip_pinch_power_grip_right_custom: dto.gripPinch?.gripPinchPowerGripRightCustom || '',
      grip_pinch_power_grip_right_text: dto.gripPinch?.gripPinchPowerGripRightText || '',
      grip_pinch_power_grip_left: dto.gripPinch?.gripPinchPowerGripLeft || '',
      grip_pinch_power_grip_left_custom: dto.gripPinch?.gripPinchPowerGripLeftCustom || '',
      grip_pinch_power_grip_left_text: dto.gripPinch?.gripPinchPowerGripLeftText || '',
      grip_pinch_lateral_pinch_right: dto.gripPinch?.gripPinchLateralPinchRight || '',
      grip_pinch_lateral_pinch_right_custom: dto.gripPinch?.gripPinchLateralPinchRightCustom || '',
      grip_pinch_lateral_pinch_right_text: dto.gripPinch?.gripPinchLateralPinchRightText || '',
      grip_pinch_lateral_pinch_left: dto.gripPinch?.gripPinchLateralPinchLeft || '',
      grip_pinch_lateral_pinch_left_custom: dto.gripPinch?.gripPinchLateralPinchLeftCustom || '',
      grip_pinch_lateral_pinch_left_text: dto.gripPinch?.gripPinchLateralPinchLeftText || '',
      'grip_pinch_tip_pinch/pincer_right': dto.gripPinch?.gripPinchTipPinchpincerRight || '',
      'grip_pinch_tip_pinch/pincer_right_custom': dto.gripPinch?.gripPinchTipPinchpincerRightCustom || '',
      'grip_pinch_tip_pinch/pincer_right_text': dto.gripPinch?.gripPinchTipPinchpincerRightText || '',
      'grip_pinch_tip_pinch/pincer_left': dto.gripPinch?.gripPinchTipPinchpincerLeft || '',
      'grip_pinch_tip_pinch/pincer_left_custom': dto.gripPinch?.gripPinchTipPinchpincerLeftCustom || '',
      'grip_pinch_tip_pinch/pincer_left_text': dto.gripPinch?.gripPinchTipPinchpincerLeftText || '',
      grip_pinch_tripod_pinch_right: dto.gripPinch?.gripPinchTripodPinchRight || '',
      grip_pinch_tripod_pinch_right_custom: dto.gripPinch?.gripPinchTripodPinchRightCustom || '',
      grip_pinch_tripod_pinch_right_text: dto.gripPinch?.gripPinchTripodPinchRightText || '',
      grip_pinch_tripod_pinch_left: dto.gripPinch?.gripPinchTripodPinchLeft || '',
      grip_pinch_tripod_pinch_left_custom: dto.gripPinch?.gripPinchTripodPinchLeftCustom || '',
      grip_pinch_tripod_pinch_left_text: dto.gripPinch?.gripPinchTripodPinchLeftText || '',
      grip_pinch_comments: dto.gripPinch?.gripPinchComments || '',
      rapid_exchange: dto.gripPinch?.rapidExchange ? 'yes' : 'no',
      repeated_grip: dto.gripPinch?.repeatedGrip ? 'yes' : 'no',
      five_level_grip: dto.gripPinch?.fiveLevelGrip ? 'yes' : 'no',

      // Gross Muscle Tests Upper
      gross_muscle_tests_upper: dto.grossMuscleTestsUpper?.grossMuscleTestsUpper ? 'yes' : 'no',
      cervical_gross_muscle_tests_upper: dto.grossMuscleTestsUpper?.cervicalGrossMuscleTestsUpper ? 'yes' : 'no',
      shoulder_gross_muscle_tests_upper: dto.grossMuscleTestsUpper?.shoulderGrossMuscleTestsUpper ? 'yes' : 'no',
      elbow_gross_muscle_tests_upper: dto.grossMuscleTestsUpper?.elbowGrossMuscleTestsUpper ? 'yes' : 'no',
      wrist_gross_muscle_tests_upper: dto.grossMuscleTestsUpper?.wristGrossMuscleTestsUpper ? 'yes' : 'no',

      // Redcord Neurac Stability Tests
      redcord_neurac_stability_tests: dto.redcordNeuracStabilityTests?.redcordNeuracStabilityTests ? 'yes' : 'no',
      upper_body_myofascial_tests: dto.redcordNeuracStabilityTests?.upperBodyMyofascialTests ? 'yes' : 'no',
      lower_body_myofascial_tests: dto.redcordNeuracStabilityTests?.lowerBodyMyofascialTests ? 'yes' : 'no',
      cervical_movements: dto.redcordNeuracStabilityTests?.cervicalMovements ? 'yes' : 'no',
      cervical_motor_control_tests: dto.redcordNeuracStabilityTests?.cervicalMotorControlTests ? 'yes' : 'no',
      lumbar_motor_control_tests: dto.redcordNeuracStabilityTests?.lumbarMotorControlTests ? 'yes' : 'no',

      // Gross Muscle Tests Trunk
      gross_muscle_tests_trunk: dto.grossMuscleTestsTrunk?.grossMuscleTestsTrunk ? 'yes' : 'no',
      gross_muscle_tests_stabilization: dto.grossMuscleTestsTrunk?.grossMuscleTestsStabilization || '',
      gross_muscle_tests_upper_abdominals: dto.grossMuscleTestsTrunk?.grossMuscleTestsUpperAbdominals || '',
      gross_muscle_tests_upper_abdominals_custom: dto.grossMuscleTestsTrunk?.grossMuscleTestsUpperAbdominalsCustom || '',
      gross_muscle_tests_quality: dto.grossMuscleTestsTrunk?.grossMuscleTestsQuality || '',
      gross_muscle_tests_quality_custom: dto.grossMuscleTestsTrunk?.grossMuscleTestsQualityCustom || '',
      gross_muscle_tests_obliques_right: dto.grossMuscleTestsTrunk?.grossMuscleTestsObliquesRight || '',
      gross_muscle_tests_obliques_right_custom: dto.grossMuscleTestsTrunk?.grossMuscleTestsObliquesRightCustom || '',
      gross_muscle_tests_obliques_left: dto.grossMuscleTestsTrunk?.grossMuscleTestsObliquesLeft || '',
      gross_muscle_tests_obliques_left_custom: dto.grossMuscleTestsTrunk?.grossMuscleTestsObliquesLeftCustom || '',
      gross_muscle_tests_trunk_extensors_right: dto.grossMuscleTestsTrunk?.grossMuscleTestsTrunkExtensorsRight || '',
      gross_muscle_tests_trunk_extensors_right_custom: dto.grossMuscleTestsTrunk?.grossMuscleTestsTrunkExtensorsRightCustom || '',
      gross_muscle_tests_trunk_extensors_left: dto.grossMuscleTestsTrunk?.grossMuscleTestsTrunkExtensorsLeft || '',
      gross_muscle_tests_trunk_extensors_left_custom: dto.grossMuscleTestsTrunk?.grossMuscleTestsTrunkExtensorsLeftCustom || '',
      gross_muscle_comments: dto.grossMuscleTestsTrunk?.grossMuscleTestsTrunkComment || '',

      // Gross Muscle Tests Lower
      gross_muscle_tests_lower: dto.grossMuscleTestsLower?.grossMuscleTestsLower ? 'yes' : 'no',
      hip_gross_muscle_tests_lower: dto.grossMuscleTestsLower?.hipGrossMuscleTestsLower ? 'yes' : 'no',
      knee_gross_muscle_tests_lower: dto.grossMuscleTestsLower?.kneeGrossMuscleTestsLower ? 'yes' : 'no',
      ankle_gross_muscle_tests_lower: dto.grossMuscleTestsLower?.ankleGrossMuscleTestsLower ? 'yes' : 'no',

      // Core Strength
      core_strength: dto.coreStrength?.coreStrength ? 'yes' : 'no',
      prone_extensioncore_strength: dto.coreStrength?.proneExtensioncoreStrength ? 'yes' : 'no',
      supine_flexion_core_strength: dto.coreStrength?.supineFlexionCoreStrength ? 'yes' : 'no',
      situps_core_strength: dto.coreStrength?.situpsCoreStrength ? 'yes' : 'no',
      pushup_core_strength: dto.coreStrength?.pushupCoreStrength ? 'yes' : 'no',

      // Manual Muscle Tests
      manual_muscle_tests: dto.manualMuscleTests?.manualMuscleTests ? 'yes' : 'no',
      manual_muscle_tests_deep_neck_flexors: dto.manualMuscleTests?.manualMuscleTestsDeepNeckFlexors || '',
      manual_muscle_tests_deep_neck_flexors_custom: dto.manualMuscleTests?.manualMuscleTestsDeepNeckFlexorsCustom || '',
      manual_muscle_testsanterior_deltoid_right: dto.manualMuscleTests?.manualMuscleTestsanteriorDeltoidRight || '',
      manual_muscle_testsanterior_deltoid_right_custom: dto.manualMuscleTests?.manualMuscleTestsanteriorDeltoidRightCustom || '',
      manual_muscle_testsanterior_deltoid_left: dto.manualMuscleTests?.manualMuscleTestsanteriorDeltoidLeft || '',
      manual_muscle_testsanterior_deltoid_left_custom: dto.manualMuscleTests?.manualMuscleTestsanteriorDeltoidLeftCustom || '',
      manual_muscle_testsmiddle_deltoid_right: dto.manualMuscleTests?.manualMuscleTestsmiddleDeltoidRight || '',
      manual_muscle_testsmiddle_deltoid_right_custom: dto.manualMuscleTests?.manualMuscleTestsmiddleDeltoidRightCustom || '',
      manual_muscle_testsmiddle_deltoid_left: dto.manualMuscleTests?.manualMuscleTestsmiddleDeltoidLeft || '',
      manual_muscle_testsmiddle_deltoid_left_custom: dto.manualMuscleTests?.manualMuscleTestsmiddleDeltoidLeftCustom || '',
      manual_muscle_testsposterior_deltoid_right: dto.manualMuscleTests?.manualMuscleTestsposteriorDeltoidRight || '',
      manual_muscle_testsposterior_deltoid_right_custom: dto.manualMuscleTests?.manualMuscleTestsposteriorDeltoidRightCustom || '',
      manual_muscle_testsposterior_deltoid_left: dto.manualMuscleTests?.manualMuscleTestsposteriorDeltoidLeft || '',
      manual_muscle_testsposterior_deltoid_left_custom: dto.manualMuscleTests?.manualMuscleTestsposteriorDeltoidLeftCustom || '',
      manual_muscle_testsupper_trapezius_right: dto.manualMuscleTests?.manualMuscleTestsupperTrapeziusRight || '',
      manual_muscle_testsupper_trapezius_right_custom: dto.manualMuscleTests?.manualMuscleTestsupperTrapeziusRightCustom || '',
      manual_muscle_testsupper_trapezius_left: dto.manualMuscleTests?.manualMuscleTestsupperTrapeziusLeft || '',
      manual_muscle_testsupper_trapezius_left_custom: dto.manualMuscleTests?.manualMuscleTestsupperTrapeziusLeftCustom || '',
      manual_muscle_testsmiddle_trapezius_right: dto.manualMuscleTests?.manualMuscleTestsmiddleTrapeziusRight || '',
      manual_muscle_testsmiddle_trapezius_right_custom: dto.manualMuscleTests?.manualMuscleTestsmiddleTrapeziusRightCustom || '',
      manual_muscle_testsmiddle_trapezius_left: dto.manualMuscleTests?.manualMuscleTestsmiddleTrapeziusLeft || '',
      manual_muscle_testsmiddle_trapezius_left_custom: dto.manualMuscleTests?.manualMuscleTestsmiddleTrapeziusLeftCustom || '',
      manual_muscle_testslower_trapezius_right: dto.manualMuscleTests?.manualMuscleTestslowerTrapeziusRight || '',
      manual_muscle_testslower_trapezius_right_custom: dto.manualMuscleTests?.manualMuscleTestslowerTrapeziusRightCustom || '',
      manual_muscle_testslower_trapezius_left: dto.manualMuscleTests?.manualMuscleTestslowerTrapeziusLeft || '',
      manual_muscle_testslower_trapezius_left_custom: dto.manualMuscleTests?.manualMuscleTestslowerTrapeziusLeftCustom || '',
      manual_muscle_testspectorals_right: dto.manualMuscleTests?.manualMuscleTestspectoralsRight || '',
      manual_muscle_testspectorals_right_custom: dto.manualMuscleTests?.manualMuscleTestspectoralsRightCustom || '',
      manual_muscle_testspectorals_left: dto.manualMuscleTests?.manualMuscleTestspectoralsLeft || '',
      manual_muscle_testspectorals_left_custom: dto.manualMuscleTests?.manualMuscleTestspectoralsLeftCustom || '',
      manual_muscle_testslatissimus_dorsi_right: dto.manualMuscleTests?.manualMuscleTestslatissimusDorsiRight || '',
      manual_muscle_testslatissimus_dorsi_right_custom: dto.manualMuscleTests?.manualMuscleTestslatissimusDorsiRightCustom || '',
      manual_muscle_testslatissimus_dorsi_left: dto.manualMuscleTests?.manualMuscleTestslatissimusDorsiLeft || '',
      manual_muscle_testslatissimus_dorsi_left_custom: dto.manualMuscleTests?.manualMuscleTestslatissimusDorsiLeftCustom || '',
      manual_muscle_testssupraspinatus_right: dto.manualMuscleTests?.manualMuscleTestssupraspinatusRight || '',
      manual_muscle_testssupraspinatus_right_custom: dto.manualMuscleTests?.manualMuscleTestssupraspinatusRightCustom || '',
      manual_muscle_testssupraspinatus_left: dto.manualMuscleTests?.manualMuscleTestssupraspinatusLeft || '',
      manual_muscle_testssupraspinatus_left_custom: dto.manualMuscleTests?.manualMuscleTestssupraspinatusLeftCustom || '',
      'manual_muscle_testsinfraspinatus/teres_minor_right': dto.manualMuscleTests?.manualMuscleTestsinfraspinatusteresMinorRight || '',
      'manual_muscle_testsinfraspinatus/teres_minor_right_custom': dto.manualMuscleTests?.manualMuscleTestsinfraspinatusteresMinorRightCustom || '',
      'manual_muscle_testsinfraspinatus/teres_minor_left': dto.manualMuscleTests?.manualMuscleTestsinfraspinatusteresMinorLeft || '',
      'manual_muscle_testsinfraspinatus/teres_minor_left_custom': dto.manualMuscleTests?.manualMuscleTestsinfraspinatusteresMinorLeftCustom || '',
      manual_muscle_testsinfraspinatus_right: dto.manualMuscleTests?.manualMuscleTestsinfraspinatusRight || '',
      manual_muscle_testsinfraspinatus_right_custom: dto.manualMuscleTests?.manualMuscleTestsinfraspinatusRightCustom || '',
      manual_muscle_testsinfraspinatus_left: dto.manualMuscleTests?.manualMuscleTestsinfraspinatusLeft || '',
      manual_muscle_testsinfraspinatus_left_custom: dto.manualMuscleTests?.manualMuscleTestsinfraspinatusLeftCustom || '',
      manual_muscle_teststeres_minor_right: dto.manualMuscleTests?.manualMuscleTeststeresMinorRight || '',
      manual_muscle_teststeres_minor_right_custom: dto.manualMuscleTests?.manualMuscleTeststeresMinorRightCustom || '',
      manual_muscle_teststeres_minor_left: dto.manualMuscleTests?.manualMuscleTeststeresMinorLeft || '',
      manual_muscle_teststeres_minor_left_custom: dto.manualMuscleTests?.manualMuscleTeststeresMinorLeftCustom || '',
      manual_muscle_testssubscapularis_right: dto.manualMuscleTests?.manualMuscleTestssubscapularisRight || '',
      manual_muscle_testssubscapularis_right_custom: dto.manualMuscleTests?.manualMuscleTestssubscapularisRightCustom || '',
      manual_muscle_testssubscapularis_left: dto.manualMuscleTests?.manualMuscleTestssubscapularisLeft || '',
      manual_muscle_testssubscapularis_left_custom: dto.manualMuscleTests?.manualMuscleTestssubscapularisLeftCustom || '',
      manual_muscle_testsserratus_anterior_right: dto.manualMuscleTests?.manualMuscleTestsserratusAnteriorRight || '',
      manual_muscle_testsserratus_anterior_right_custom: dto.manualMuscleTests?.manualMuscleTestsserratusAnteriorRightCustom || '',
      manual_muscle_testsserratus_anterior_left: dto.manualMuscleTests?.manualMuscleTestsserratusAnteriorLeft || '',
      manual_muscle_testsserratus_anterior_left_custom: dto.manualMuscleTests?.manualMuscleTestsserratusAnteriorLeftCustom || '',
      manual_muscle_testsrhomboids_right: dto.manualMuscleTests?.manualMuscleTestsrhomboidsRight || '',
      manual_muscle_testsrhomboids_right_custom: dto.manualMuscleTests?.manualMuscleTestsrhomboidsRightCustom || '',
      manual_muscle_testsrhomboids_left: dto.manualMuscleTests?.manualMuscleTestsrhomboidsLeft || '',
      manual_muscle_testsrhomboids_left_custom: dto.manualMuscleTests?.manualMuscleTestsrhomboidsLeftCustom || '',
      manual_muscle_testsbiceps_right: dto.manualMuscleTests?.manualMuscleTestsbicepsRight || '',
      manual_muscle_testsbiceps_right_custom: dto.manualMuscleTests?.manualMuscleTestsbicepsRightCustom || '',
      manual_muscle_testsbiceps_left: dto.manualMuscleTests?.manualMuscleTestsbicepsLeft || '',
      manual_muscle_testsbiceps_left_custom: dto.manualMuscleTests?.manualMuscleTestsbicepsLeftCustom || '',
      manual_muscle_teststriceps_right: dto.manualMuscleTests?.manualMuscleTeststricepsRight || '',
      manual_muscle_teststriceps_right_custom: dto.manualMuscleTests?.manualMuscleTeststricepsRightCustom || '',
      manual_muscle_teststriceps_left: dto.manualMuscleTests?.manualMuscleTeststricepsLeft || '',
      manual_muscle_teststriceps_left_custom: dto.manualMuscleTests?.manualMuscleTeststricepsLeftCustom || '',
      manual_muscle_testsbrachioradialis_right: dto.manualMuscleTests?.manualMuscleTestsbrachioradialisRight || '',
      manual_muscle_testsbrachioradialis_right_custom: dto.manualMuscleTests?.manualMuscleTestsbrachioradialisRightCustom || '',
      manual_muscle_testsbrachioradialis_left: dto.manualMuscleTests?.manualMuscleTestsbrachioradialisLeft || '',
      manual_muscle_testsbrachioradialis_left_custom: dto.manualMuscleTests?.manualMuscleTestsbrachioradialisLeftCustom || '',
      manual_muscle_testspronator_teres_right: dto.manualMuscleTests?.manualMuscleTestspronatorTeresRight || '',
      manual_muscle_testspronator_teres_right_custom: dto.manualMuscleTests?.manualMuscleTestspronatorTeresRightCustom || '',
      manual_muscle_testspronator_teres_left: dto.manualMuscleTests?.manualMuscleTestspronatorTeresLeft || '',
      manual_muscle_testspronator_teres_left_custom: dto.manualMuscleTests?.manualMuscleTestspronatorTeresLeftCustom || '',
      manual_muscle_testswrist_extensors_right: dto.manualMuscleTests?.manualMuscleTestswristExtensorsRight || '',
      manual_muscle_testswrist_extensors_right_custom: dto.manualMuscleTests?.manualMuscleTestswristExtensorsRightCustom || '',
      manual_muscle_testswrist_extensors_left: dto.manualMuscleTests?.manualMuscleTestswristExtensorsLeft || '',
      manual_muscle_testswrist_extensors_left_custom: dto.manualMuscleTests?.manualMuscleTestswristExtensorsLeftCustom || '',
      manual_muscle_testswrist_flexors_right: dto.manualMuscleTests?.manualMuscleTestswristFlexorsRight || '',
      manual_muscle_testswrist_flexors_right_custom: dto.manualMuscleTests?.manualMuscleTestswristFlexorsRightCustom || '',
      manual_muscle_testswrist_flexors_left: dto.manualMuscleTests?.manualMuscleTestswristFlexorsLeft || '',
      manual_muscle_testswrist_flexors_left_custom: dto.manualMuscleTests?.manualMuscleTestswristFlexorsLeftCustom || '',
      manual_muscle_testssupinator_right: dto.manualMuscleTests?.manualMuscleTestssupinatorRight || '',
      manual_muscle_testssupinator_right_custom: dto.manualMuscleTests?.manualMuscleTestssupinatorRightCustom || '',
      manual_muscle_testssupinator_left: dto.manualMuscleTests?.manualMuscleTestssupinatorLeft || '',
      manual_muscle_testssupinator_left_custom: dto.manualMuscleTests?.manualMuscleTestssupinatorLeftCustom || '',
      manual_muscle_testsextensor_digitorum_communis_right: dto.manualMuscleTests?.manualMuscleTestsextensorDigitorumCommunisRight || '',
      manual_muscle_testsextensor_digitorum_communis_right_custom: dto.manualMuscleTests?.manualMuscleTestsextensorDigitorumCommunisRightCustom || '',
      manual_muscle_testsextensor_digitorum_communis_left: dto.manualMuscleTests?.manualMuscleTestsextensorDigitorumCommunisLeft || '',
      manual_muscle_testsextensor_digitorum_communis_left_custom: dto.manualMuscleTests?.manualMuscleTestsextensorDigitorumCommunisLeftCustom || '',
      manual_muscle_testsiliopsoas_right: dto.manualMuscleTests?.manualMuscleTestsiliopsoasRight || '',
      manual_muscle_testsiliopsoas_right_custom: dto.manualMuscleTests?.manualMuscleTestsiliopsoasRightCustom || '',
      manual_muscle_testsiliopsoas_left: dto.manualMuscleTests?.manualMuscleTestsiliopsoasLeft || '',
      manual_muscle_testsiliopsoas_left_custom: dto.manualMuscleTests?.manualMuscleTestsiliopsoasLeftCustom || '',
      manual_muscle_testsgluteus_maximus_right: dto.manualMuscleTests?.manualMuscleTestsgluteusMaximusRight || '',
      manual_muscle_testsgluteus_maximus_right_custom: dto.manualMuscleTests?.manualMuscleTestsgluteusMaximusRightCustom || '',
      manual_muscle_testsgluteus_maximus_left: dto.manualMuscleTests?.manualMuscleTestsgluteusMaximusLeft || '',
      manual_muscle_testsgluteus_maximus_left_custom: dto.manualMuscleTests?.manualMuscleTestsgluteusMaximusLeftCustom || '',
      manual_muscle_testsgluteus_medius_right: dto.manualMuscleTests?.manualMuscleTestsgluteusMediusRight || '',
      manual_muscle_testsgluteus_medius_right_custom: dto.manualMuscleTests?.manualMuscleTestsgluteusMediusRightCustom || '',
      manual_muscle_testsgluteus_medius_left: dto.manualMuscleTests?.manualMuscleTestsgluteusMediusLeft || '',
      manual_muscle_testsgluteus_medius_left_custom: dto.manualMuscleTests?.manualMuscleTestsgluteusMediusLeftCustom || '',
      manual_muscle_testsquadriceps_right: dto.manualMuscleTests?.manualMuscleTestsquadricepsRight || '',
      manual_muscle_testsquadriceps_right_custom: dto.manualMuscleTests?.manualMuscleTestsquadricepsRightCustom || '',
      manual_muscle_testsquadriceps_left: dto.manualMuscleTests?.manualMuscleTestsquadricepsLeft || '',
      manual_muscle_testsquadriceps_left_custom: dto.manualMuscleTests?.manualMuscleTestsquadricepsLeftCustom || '',
      manual_muscle_testshamstrings_right: dto.manualMuscleTests?.manualMuscleTestshamstringsRight || '',
      manual_muscle_testshamstrings_right_custom: dto.manualMuscleTests?.manualMuscleTestshamstringsRightCustom || '',
      manual_muscle_testshamstrings_left: dto.manualMuscleTests?.manualMuscleTestshamstringsLeft || '',
      manual_muscle_testshamstrings_left_custom: dto.manualMuscleTests?.manualMuscleTestshamstringsLeftCustom || '',
      manual_muscle_testsadductors_right: dto.manualMuscleTests?.manualMuscleTestsadductorsRight || '',
      manual_muscle_testsadductors_right_custom: dto.manualMuscleTests?.manualMuscleTestsadductorsRightCustom || '',
      manual_muscle_testsadductors_left: dto.manualMuscleTests?.manualMuscleTestsadductorsLeft || '',
      manual_muscle_testsadductors_left_custom: dto.manualMuscleTests?.manualMuscleTestsadductorsLeftCustom || '',
      manual_muscle_testsanterior_tibialis_right: dto.manualMuscleTests?.manualMuscleTestsanteriorTibialisRight || '',
      manual_muscle_testsanterior_tibialis_right_custom: dto.manualMuscleTests?.manualMuscleTestsanteriorTibialisRightCustom || '',
      manual_muscle_testsanterior_tibialis_left: dto.manualMuscleTests?.manualMuscleTestsanteriorTibialisLeft || '',
      manual_muscle_testsanterior_tibialis_left_custom: dto.manualMuscleTests?.manualMuscleTestsanteriorTibialisLeftCustom || '',
      manual_muscle_testsposterior_tibialis_right: dto.manualMuscleTests?.manualMuscleTestsposteriorTibialisRight || '',
      manual_muscle_testsposterior_tibialis_right_custom: dto.manualMuscleTests?.manualMuscleTestsposteriorTibialisRightCustom || '',
      manual_muscle_testsposterior_tibialis_left: dto.manualMuscleTests?.manualMuscleTestsposteriorTibialisLeft || '',
      manual_muscle_testsposterior_tibialis_left_custom: dto.manualMuscleTests?.manualMuscleTestsposteriorTibialisLeftCustom || '',
      manual_muscle_testsgastrocnemius_right: dto.manualMuscleTests?.manualMuscleTestsgastrocnemiusRight || '',
      manual_muscle_testsgastrocnemius_right_custom: dto.manualMuscleTests?.manualMuscleTestsgastrocnemiusRightCustom || '',
      manual_muscle_testsgastrocnemius_left: dto.manualMuscleTests?.manualMuscleTestsgastrocnemiusLeft || '',
      manual_muscle_testsgastrocnemius_left_custom: dto.manualMuscleTests?.manualMuscleTestsgastrocnemiusLeftCustom || '',
      manual_muscle_testssoleus_right: dto.manualMuscleTests?.manualMuscleTestssoleusRight || '',
      manual_muscle_testssoleus_right_custom: dto.manualMuscleTests?.manualMuscleTestssoleusRightCustom || '',
      manual_muscle_testssoleus_left: dto.manualMuscleTests?.manualMuscleTestssoleusLeft || '',
      manual_muscle_testssoleus_left_custom: dto.manualMuscleTests?.manualMuscleTestssoleusLeftCustom || '',
      manual_muscle_testsperoneals_right: dto.manualMuscleTests?.manualMuscleTestsperonealsRight || '',
      manual_muscle_testsperoneals_right_custom: dto.manualMuscleTests?.manualMuscleTestsperonealsRightCustom || '',
      manual_muscle_testsperoneals_left: dto.manualMuscleTests?.manualMuscleTestsperonealsLeft || '',
      manual_muscle_testsperoneals_left_custom: dto.manualMuscleTests?.manualMuscleTestsperonealsLeftCustom || '',
      manual_muscle_testsextensor_hallucis_right: dto.manualMuscleTests?.manualMuscleTestsextensorHallucisRight || '',
      manual_muscle_testsextensor_hallucis_right_custom: dto.manualMuscleTests?.manualMuscleTestsextensorHallucisRightCustom || '',
      manual_muscle_testsextensor_hallucis_left: dto.manualMuscleTests?.manualMuscleTestsextensorHallucisLeft || '',
      manual_muscle_testsextensor_hallucis_left_custom: dto.manualMuscleTests?.manualMuscleTestsextensorHallucisLeftCustom || '',
      manual_muscle_testsflexor_hallucis_right: dto.manualMuscleTests?.manualMuscleTestsflexorHallucisRight || '',
      manual_muscle_testsflexor_hallucis_right_custom: dto.manualMuscleTests?.manualMuscleTestsflexorHallucisRightCustom || '',
      manual_muscle_testsflexor_hallucis_left: dto.manualMuscleTests?.manualMuscleTestsflexorHallucisLeft || '',
      manual_muscle_testsflexor_hallucis_left_custom: dto.manualMuscleTests?.manualMuscleTestsflexorHallucisLeftCustom || '',
      manual_muscle_testsflexor_digitorum_longus_right: dto.manualMuscleTests?.manualMuscleTestsflexorDigitorumLongusRight || '',
      manual_muscle_testsflexor_digitorum_longus_right_custom: dto.manualMuscleTests?.manualMuscleTestsflexorDigitorumLongusRightCustom || '',
      manual_muscle_testsflexor_digitorum_longus_left: dto.manualMuscleTests?.manualMuscleTestsflexorDigitorumLongusLeft || '',
      manual_muscle_testsflexor_digitorum_longus_left_custom: dto.manualMuscleTests?.manualMuscleTestsflexorDigitorumLongusLeftCustom || '',
      manual_muscle_tests_comments: dto.manualMuscleTests?.manualMuscleTestsComments || '',

      // Additional Comments
      additional_comments: dto.additionalComments?.additionalComments ? 'yes' : 'no',
      additional_comments_text: dto.additionalComments?.additionalCommentsText || ''
    };
  }

  /**
   * Converts form values to DTO model
   * @param formValue Form values object
   * @returns Strength DTO
   */
  toModel(formValue: any): Strength {
    const noLimitationsNoted: NoLimitationsNoted = {
      noLimitationsNoted: formValue.no_limitations_noted === 'yes',
      uperExtremity: formValue.uper_extremity || false,
      lowerExtremity: formValue.lower_extremity || false
    };

    const selectiveTissueTensionUpper: SelectiveTissueTensionUpper = {
      selectiveTissueTensionUpper: formValue.selective_tissue_tension_upper === 'yes',
      cervical: formValue.cervical === 'yes',
      trunk: formValue.trunk === 'yes',
      backRibs: formValue.back_ribs === 'yes',
      shoulder: formValue.shoulder === 'yes',
      elbow: formValue.elbow === 'yes',
      wrist: formValue.wrist === 'yes',
      hand: formValue.hand === 'yes'
    };

    const selectiveTissueTensionLower: SelectiveTissueTensionLower = {
      selectiveTissueTensionLower: formValue.selective_tissue_tension_lower === 'yes',
      hip: formValue.hip === 'yes',
      knee: formValue.knee === 'yes',
      ankle: formValue.ankle === 'yes',
      foot: formValue.foot === 'yes'
    };

    const gripPinch: GripPinch = {
      gripPinch: formValue.grip_pinch === 'yes',
      gripPinchPowerGripRight: formValue.grip_pinch_power_grip_right || '',
      gripPinchPowerGripRightCustom: formValue.grip_pinch_power_grip_right_custom || '',
      gripPinchPowerGripRightText: formValue.grip_pinch_power_grip_right_text || '',
      gripPinchPowerGripLeft: formValue.grip_pinch_power_grip_left || '',
      gripPinchPowerGripLeftCustom: formValue.grip_pinch_power_grip_left_custom || '',
      gripPinchPowerGripLeftText: formValue.grip_pinch_power_grip_left_text || '',
      gripPinchLateralPinchRight: formValue.grip_pinch_lateral_pinch_right || '',
      gripPinchLateralPinchRightCustom: formValue.grip_pinch_lateral_pinch_right_custom || '',
      gripPinchLateralPinchRightText: formValue.grip_pinch_lateral_pinch_right_text || '',
      gripPinchLateralPinchLeft: formValue.grip_pinch_lateral_pinch_left || '',
      gripPinchLateralPinchLeftCustom: formValue.grip_pinch_lateral_pinch_left_custom || '',
      gripPinchLateralPinchLeftText: formValue.grip_pinch_lateral_pinch_left_text || '',
      gripPinchTipPinchpincerRight: formValue['grip_pinch_tip_pinch/pincer_right'] || '',
      gripPinchTipPinchpincerRightCustom: formValue['grip_pinch_tip_pinch/pincer_right_custom'] || '',
      gripPinchTipPinchpincerRightText: formValue['grip_pinch_tip_pinch/pincer_right_text'] || '',
      gripPinchTipPinchpincerLeft: formValue['grip_pinch_tip_pinch/pincer_left'] || '',
      gripPinchTipPinchpincerLeftCustom: formValue['grip_pinch_tip_pinch/pincer_left_custom'] || '',
      gripPinchTipPinchpincerLeftText: formValue['grip_pinch_tip_pinch/pincer_left_text'] || '',
      gripPinchTripodPinchRight: formValue.grip_pinch_tripod_pinch_right || '',
      gripPinchTripodPinchRightCustom: formValue.grip_pinch_tripod_pinch_right_custom || '',
      gripPinchTripodPinchRightText: formValue.grip_pinch_tripod_pinch_right_text || '',
      gripPinchTripodPinchLeft: formValue.grip_pinch_tripod_pinch_left || '',
      gripPinchTripodPinchLeftCustom: formValue.grip_pinch_tripod_pinch_left_custom || '',
      gripPinchTripodPinchLeftText: formValue.grip_pinch_tripod_pinch_left_text || '',
      gripPinchComments: formValue.grip_pinch_comments || '',
      rapidExchange: formValue.rapid_exchange === 'yes',
      repeatedGrip: formValue.repeated_grip === 'yes',
      fiveLevelGrip: formValue.five_level_grip === 'yes'
    };

    const grossMuscleTestsUpper: GrossMuscleTestsUpper = {
      grossMuscleTestsUpper: formValue.gross_muscle_tests_upper === 'yes',
      cervicalGrossMuscleTestsUpper: formValue.cervical_gross_muscle_tests_upper === 'yes',
      shoulderGrossMuscleTestsUpper: formValue.shoulder_gross_muscle_tests_upper === 'yes',
      elbowGrossMuscleTestsUpper: formValue.elbow_gross_muscle_tests_upper === 'yes',
      wristGrossMuscleTestsUpper: formValue.wrist_gross_muscle_tests_upper === 'yes'
    };

    const redcordNeuracStabilityTests: RedcordNeuracStabilityTests = {
      redcordNeuracStabilityTests: formValue.redcord_neurac_stability_tests === 'yes',
      upperBodyMyofascialTests: formValue.upper_body_myofascial_tests === 'yes',
      lowerBodyMyofascialTests: formValue.lower_body_myofascial_tests === 'yes',
      cervicalMovements: formValue.cervical_movements === 'yes',
      cervicalMotorControlTests: formValue.cervical_motor_control_tests === 'yes',
      lumbarMotorControlTests: formValue.lumbar_motor_control_tests === 'yes'
    };

    const grossMuscleTestsTrunk: GrossMuscleTestsTrunk = {
      grossMuscleTestsTrunk: formValue.gross_muscle_tests_trunk === 'yes',
      grossMuscleTestsStabilization: formValue.gross_muscle_tests_stabilization || '',
      grossMuscleTestsUpperAbdominals: formValue.gross_muscle_tests_upper_abdominals,
      grossMuscleTestsUpperAbdominalsCustom: formValue.gross_muscle_tests_upper_abdominals_custom || '',
      grossMuscleTestsQuality: formValue.gross_muscle_tests_quality || '',
      grossMuscleTestsQualityCustom: formValue.gross_muscle_tests_quality_custom || '',
      grossMuscleTestsObliquesRight: formValue.gross_muscle_tests_obliques_right || '',
      grossMuscleTestsObliquesRightCustom: formValue.gross_muscle_tests_obliques_right_custom || '',
      grossMuscleTestsObliquesLeft: formValue.gross_muscle_tests_obliques_left || '',
      grossMuscleTestsObliquesLeftCustom: formValue.gross_muscle_tests_obliques_left_custom || '',
      grossMuscleTestsTrunkExtensorsRight: formValue.gross_muscle_tests_trunk_extensors_right || '',
      grossMuscleTestsTrunkExtensorsRightCustom: formValue.gross_muscle_tests_trunk_extensors_right_custom || '',
      grossMuscleTestsTrunkExtensorsLeft: formValue.gross_muscle_tests_trunk_extensors_left || '',
      grossMuscleTestsTrunkExtensorsLeftCustom: formValue.gross_muscle_tests_trunk_extensors_left_custom || '',
      grossMuscleTestsTrunkComment: formValue.gross_muscle_comments || ''
    };

    const grossMuscleTestsLower: GrossMuscleTestsLower = {
      grossMuscleTestsLower: formValue.gross_muscle_tests_lower === 'yes',
      hipGrossMuscleTestsLower: formValue.hip_gross_muscle_tests_lower === 'yes',
      kneeGrossMuscleTestsLower: formValue.knee_gross_muscle_tests_lower === 'yes',
      ankleGrossMuscleTestsLower: formValue.ankle_gross_muscle_tests_lower === 'yes'
    };

    const coreStrength: CoreStrength = {
      coreStrength: formValue.core_strength === 'yes',
      proneExtensioncoreStrength: formValue.prone_extensioncore_strength === 'yes',
      supineFlexionCoreStrength: formValue.supine_flexion_core_strength === 'yes',
      situpsCoreStrength: formValue.situps_core_strength === 'yes',
      pushupCoreStrength: formValue.pushup_core_strength === 'yes'
    };

    const manualMuscleTests: ManualMuscleTests = {
      manualMuscleTests: formValue.manual_muscle_tests === 'yes',
      manualMuscleTestsDeepNeckFlexors: formValue.manual_muscle_tests_deep_neck_flexors || '',
      manualMuscleTestsDeepNeckFlexorsCustom: formValue.manual_muscle_tests_deep_neck_flexors_custom || '',
      manualMuscleTestsanteriorDeltoidRight: formValue.manual_muscle_testsanterior_deltoid_right || '',
      manualMuscleTestsanteriorDeltoidRightCustom: formValue.manual_muscle_testsanterior_deltoid_right_custom || '',
      manualMuscleTestsanteriorDeltoidLeft: formValue.manual_muscle_testsanterior_deltoid_left || '',
      manualMuscleTestsanteriorDeltoidLeftCustom: formValue.manual_muscle_testsanterior_deltoid_left_custom || '',
      manualMuscleTestsmiddleDeltoidRight: formValue.manual_muscle_testsmiddle_deltoid_right || '',
      manualMuscleTestsmiddleDeltoidRightCustom: formValue.manual_muscle_testsmiddle_deltoid_right_custom || '',
      manualMuscleTestsmiddleDeltoidLeft: formValue.manual_muscle_testsmiddle_deltoid_left || '',
      manualMuscleTestsmiddleDeltoidLeftCustom: formValue.manual_muscle_testsmiddle_deltoid_left_custom || '',
      manualMuscleTestsposteriorDeltoidRight: formValue.manual_muscle_testsposterior_deltoid_right || '',
      manualMuscleTestsposteriorDeltoidRightCustom: formValue.manual_muscle_testsposterior_deltoid_right_custom || '',
      manualMuscleTestsposteriorDeltoidLeft: formValue.manual_muscle_testsposterior_deltoid_left || '',
      manualMuscleTestsposteriorDeltoidLeftCustom: formValue.manual_muscle_testsposterior_deltoid_left_custom || '',
      manualMuscleTestsupperTrapeziusRight: formValue.manual_muscle_testsupper_trapezius_right || '',
      manualMuscleTestsupperTrapeziusRightCustom: formValue.manual_muscle_testsupper_trapezius_right_custom || '',
      manualMuscleTestsupperTrapeziusLeft: formValue.manual_muscle_testsupper_trapezius_left || '',
      manualMuscleTestsupperTrapeziusLeftCustom: formValue.manual_muscle_testsupper_trapezius_left_custom || '',
      manualMuscleTestsmiddleTrapeziusRight: formValue.manual_muscle_testsmiddle_trapezius_right || '',
      manualMuscleTestsmiddleTrapeziusRightCustom: formValue.manual_muscle_testsmiddle_trapezius_right_custom || '',
      manualMuscleTestsmiddleTrapeziusLeft: formValue.manual_muscle_testsmiddle_trapezius_left || '',
      manualMuscleTestsmiddleTrapeziusLeftCustom: formValue.manual_muscle_testsmiddle_trapezius_left_custom || '',
      manualMuscleTestslowerTrapeziusRight: formValue.manual_muscle_testslower_trapezius_right || '',
      manualMuscleTestslowerTrapeziusRightCustom: formValue.manual_muscle_testslower_trapezius_right_custom || '',
      manualMuscleTestslowerTrapeziusLeft: formValue.manual_muscle_testslower_trapezius_left || '',
      manualMuscleTestslowerTrapeziusLeftCustom: formValue.manual_muscle_testslower_trapezius_left_custom || '',
      manualMuscleTestspectoralsRight: formValue.manual_muscle_testspectorals_right || '',
      manualMuscleTestspectoralsRightCustom: formValue.manual_muscle_testspectorals_right_custom || '',
      manualMuscleTestspectoralsLeft: formValue.manual_muscle_testspectorals_left || '',
      manualMuscleTestspectoralsLeftCustom: formValue.manual_muscle_testspectorals_left_custom || '',
      manualMuscleTestslatissimusDorsiRight: formValue.manual_muscle_testslatissimus_dorsi_right || '',
      manualMuscleTestslatissimusDorsiRightCustom: formValue.manual_muscle_testslatissimus_dorsi_right_custom || '',
      manualMuscleTestslatissimusDorsiLeft: formValue.manual_muscle_testslatissimus_dorsi_left || '',
      manualMuscleTestslatissimusDorsiLeftCustom: formValue.manual_muscle_testslatissimus_dorsi_left_custom || '',
      manualMuscleTestssupraspinatusRight: formValue.manual_muscle_testssupraspinatus_right || '',
      manualMuscleTestssupraspinatusRightCustom: formValue.manual_muscle_testssupraspinatus_right_custom || '',
      manualMuscleTestssupraspinatusLeft: formValue.manual_muscle_testssupraspinatus_left || '',
      manualMuscleTestssupraspinatusLeftCustom: formValue.manual_muscle_testssupraspinatus_left_custom || '',
      manualMuscleTestsinfraspinatusteresMinorRight: formValue['manual_muscle_testsinfraspinatus/teres_minor_right'] || '',
      manualMuscleTestsinfraspinatusteresMinorRightCustom: formValue['manual_muscle_testsinfraspinatus/teres_minor_right_custom'] || '',
      manualMuscleTestsinfraspinatusteresMinorLeft: formValue['manual_muscle_testsinfraspinatus/teres_minor_left'] || '',
      manualMuscleTestsinfraspinatusteresMinorLeftCustom: formValue['manual_muscle_testsinfraspinatus/teres_minor_left_custom'] || '',
      manualMuscleTestsinfraspinatusRight: formValue.manual_muscle_testsinfraspinatus_right || '',
      manualMuscleTestsinfraspinatusRightCustom: formValue.manual_muscle_testsinfraspinatus_right_custom || '',
      manualMuscleTestsinfraspinatusLeft: formValue.manual_muscle_testsinfraspinatus_left || '',
      manualMuscleTestsinfraspinatusLeftCustom: formValue.manual_muscle_testsinfraspinatus_left_custom || '',
      manualMuscleTeststeresMinorRight: formValue.manual_muscle_teststeres_minor_right || '',
      manualMuscleTeststeresMinorRightCustom: formValue.manual_muscle_teststeres_minor_right_custom || '',
      manualMuscleTeststeresMinorLeft: formValue.manual_muscle_teststeres_minor_left || '',
      manualMuscleTeststeresMinorLeftCustom: formValue.manual_muscle_teststeres_minor_left_custom || '',
      manualMuscleTestssubscapularisRight: formValue.manual_muscle_testssubscapularis_right || '',
      manualMuscleTestssubscapularisRightCustom: formValue.manual_muscle_testssubscapularis_right_custom || '',
      manualMuscleTestssubscapularisLeft: formValue.manual_muscle_testssubscapularis_left || '',
      manualMuscleTestssubscapularisLeftCustom: formValue.manual_muscle_testssubscapularis_left_custom || '',
      manualMuscleTestsserratusAnteriorRight: formValue.manual_muscle_testsserratus_anterior_right || '',
      manualMuscleTestsserratusAnteriorRightCustom: formValue.manual_muscle_testsserratus_anterior_right_custom || '',
      manualMuscleTestsserratusAnteriorLeft: formValue.manual_muscle_testsserratus_anterior_left || '',
      manualMuscleTestsserratusAnteriorLeftCustom: formValue.manual_muscle_testsserratus_anterior_left_custom || '',
      manualMuscleTestsrhomboidsRight: formValue.manual_muscle_testsrhomboids_right || '',
      manualMuscleTestsrhomboidsRightCustom: formValue.manual_muscle_testsrhomboids_right_custom || '',
      manualMuscleTestsrhomboidsLeft: formValue.manual_muscle_testsrhomboids_left || '',
      manualMuscleTestsrhomboidsLeftCustom: formValue.manual_muscle_testsrhomboids_left_custom || '',
      manualMuscleTestsbicepsRight: formValue.manual_muscle_testsbiceps_right || '',
      manualMuscleTestsbicepsRightCustom: formValue.manual_muscle_testsbiceps_right_custom || '',
      manualMuscleTestsbicepsLeft: formValue.manual_muscle_testsbiceps_left || '',
      manualMuscleTestsbicepsLeftCustom: formValue.manual_muscle_testsbiceps_left_custom || '',
      manualMuscleTeststricepsRight: formValue.manual_muscle_teststriceps_right || '',
      manualMuscleTeststricepsRightCustom: formValue.manual_muscle_teststriceps_right_custom || '',
      manualMuscleTeststricepsLeft: formValue.manual_muscle_teststriceps_left || '',
      manualMuscleTeststricepsLeftCustom: formValue.manual_muscle_teststriceps_left_custom || '',
      manualMuscleTestsbrachioradialisRight: formValue.manual_muscle_testsbrachioradialis_right || '',
      manualMuscleTestsbrachioradialisRightCustom: formValue.manual_muscle_testsbrachioradialis_right_custom || '',
      manualMuscleTestsbrachioradialisLeft: formValue.manual_muscle_testsbrachioradialis_left || '',
      manualMuscleTestsbrachioradialisLeftCustom: formValue.manual_muscle_testsbrachioradialis_left_custom || '',
      manualMuscleTestspronatorTeresRight: formValue.manual_muscle_testspronator_teres_right || '',
      manualMuscleTestspronatorTeresRightCustom: formValue.manual_muscle_testspronator_teres_right_custom || '',
      manualMuscleTestspronatorTeresLeft: formValue.manual_muscle_testspronator_teres_left || '',
      manualMuscleTestspronatorTeresLeftCustom: formValue.manual_muscle_testspronator_teres_left_custom || '',
      manualMuscleTestswristExtensorsRight: formValue.manual_muscle_testswrist_extensors_right || '',
      manualMuscleTestswristExtensorsRightCustom: formValue.manual_muscle_testswrist_extensors_right_custom || '',
      manualMuscleTestswristExtensorsLeft: formValue.manual_muscle_testswrist_extensors_left || '',
      manualMuscleTestswristExtensorsLeftCustom: formValue.manual_muscle_testswrist_extensors_left_custom || '',
      manualMuscleTestswristFlexorsRight: formValue.manual_muscle_testswrist_flexors_right || '',
      manualMuscleTestswristFlexorsRightCustom: formValue.manual_muscle_testswrist_flexors_right_custom || '',
      manualMuscleTestswristFlexorsLeft: formValue.manual_muscle_testswrist_flexors_left || '',
      manualMuscleTestswristFlexorsLeftCustom: formValue.manual_muscle_testswrist_flexors_left_custom || '',
      manualMuscleTestssupinatorRight: formValue.manual_muscle_testssupinator_right || '',
      manualMuscleTestssupinatorRightCustom: formValue.manual_muscle_testssupinator_right_custom || '',
      manualMuscleTestssupinatorLeft: formValue.manual_muscle_testssupinator_left || '',
      manualMuscleTestssupinatorLeftCustom: formValue.manual_muscle_testssupinator_left_custom || '',
      manualMuscleTestsextensorDigitorumCommunisRight: formValue.manual_muscle_testsextensor_digitorum_communis_right || '',
      manualMuscleTestsextensorDigitorumCommunisRightCustom: formValue.manual_muscle_testsextensor_digitorum_communis_right_custom || '',
      manualMuscleTestsextensorDigitorumCommunisLeft: formValue.manual_muscle_testsextensor_digitorum_communis_left || '',
      manualMuscleTestsextensorDigitorumCommunisLeftCustom: formValue.manual_muscle_testsextensor_digitorum_communis_left_custom || '',
      manualMuscleTestsiliopsoasRight: formValue.manual_muscle_testsiliopsoas_right || '',
      manualMuscleTestsiliopsoasRightCustom: formValue.manual_muscle_testsiliopsoas_right_custom || '',
      manualMuscleTestsiliopsoasLeft: formValue.manual_muscle_testsiliopsoas_left || '',
      manualMuscleTestsiliopsoasLeftCustom: formValue.manual_muscle_testsiliopsoas_left_custom || '',
      manualMuscleTestsgluteusMaximusRight: formValue.manual_muscle_testsgluteus_maximus_right || '',
      manualMuscleTestsgluteusMaximusRightCustom: formValue.manual_muscle_testsgluteus_maximus_right_custom || '',
      manualMuscleTestsgluteusMaximusLeft: formValue.manual_muscle_testsgluteus_maximus_left || '',
      manualMuscleTestsgluteusMaximusLeftCustom: formValue.manual_muscle_testsgluteus_maximus_left_custom || '',
      manualMuscleTestsgluteusMediusRight: formValue.manual_muscle_testsgluteus_medius_right || '',
      manualMuscleTestsgluteusMediusRightCustom: formValue.manual_muscle_testsgluteus_medius_right_custom || '',
      manualMuscleTestsgluteusMediusLeft: formValue.manual_muscle_testsgluteus_medius_left || '',
      manualMuscleTestsgluteusMediusLeftCustom: formValue.manual_muscle_testsgluteus_medius_left_custom || '',
      manualMuscleTestsquadricepsRight: formValue.manual_muscle_testsquadriceps_right || '',
      manualMuscleTestsquadricepsRightCustom: formValue.manual_muscle_testsquadriceps_right_custom || '',
      manualMuscleTestsquadricepsLeft: formValue.manual_muscle_testsquadriceps_left || '',
      manualMuscleTestsquadricepsLeftCustom: formValue.manual_muscle_testsquadriceps_left_custom || '',
      manualMuscleTestshamstringsRight: formValue.manual_muscle_testshamstrings_right || '',
      manualMuscleTestshamstringsRightCustom: formValue.manual_muscle_testshamstrings_right_custom || '',
      manualMuscleTestshamstringsLeft: formValue.manual_muscle_testshamstrings_left || '',
      manualMuscleTestshamstringsLeftCustom: formValue.manual_muscle_testshamstrings_left_custom || '',
      manualMuscleTestsadductorsRight: formValue.manual_muscle_testsadductors_right || '',
      manualMuscleTestsadductorsRightCustom: formValue.manual_muscle_testsadductors_right_custom || '',
      manualMuscleTestsadductorsLeft: formValue.manual_muscle_testsadductors_left || '',
      manualMuscleTestsadductorsLeftCustom: formValue.manual_muscle_testsadductors_left_custom || '',
      manualMuscleTestsanteriorTibialisRight: formValue.manual_muscle_testsanterior_tibialis_right || '',
      manualMuscleTestsanteriorTibialisRightCustom: formValue.manual_muscle_testsanterior_tibialis_right_custom || '',
      manualMuscleTestsanteriorTibialisLeft: formValue.manual_muscle_testsanterior_tibialis_left || '',
      manualMuscleTestsanteriorTibialisLeftCustom: formValue.manual_muscle_testsanterior_tibialis_left_custom || '',
      manualMuscleTestsposteriorTibialisRight: formValue.manual_muscle_testsposterior_tibialis_right || '',
      manualMuscleTestsposteriorTibialisRightCustom: formValue.manual_muscle_testsposterior_tibialis_right_custom || '',
      manualMuscleTestsposteriorTibialisLeft: formValue.manual_muscle_testsposterior_tibialis_left || '',
      manualMuscleTestsposteriorTibialisLeftCustom: formValue.manual_muscle_testsposterior_tibialis_left_custom || '',
      manualMuscleTestsgastrocnemiusRight: formValue.manual_muscle_testsgastrocnemius_right || '',
      manualMuscleTestsgastrocnemiusRightCustom: formValue.manual_muscle_testsgastrocnemius_right_custom || '',
      manualMuscleTestsgastrocnemiusLeft: formValue.manual_muscle_testsgastrocnemius_left || '',
      manualMuscleTestsgastrocnemiusLeftCustom: formValue.manual_muscle_testsgastrocnemius_left_custom || '',
      manualMuscleTestssoleusRight: formValue.manual_muscle_testssoleus_right || '',
      manualMuscleTestssoleusRightCustom: formValue.manual_muscle_testssoleus_right_custom || '',
      manualMuscleTestssoleusLeft: formValue.manual_muscle_testssoleus_left || '',
      manualMuscleTestssoleusLeftCustom: formValue.manual_muscle_testssoleus_left_custom || '',
      manualMuscleTestsperonealsRight: formValue.manual_muscle_testsperoneals_right || '',
      manualMuscleTestsperonealsRightCustom: formValue.manual_muscle_testsperoneals_right_custom || '',
      manualMuscleTestsperonealsLeft: formValue.manual_muscle_testsperoneals_left || '',
      manualMuscleTestsperonealsLeftCustom: formValue.manual_muscle_testsperoneals_left_custom || '',
      manualMuscleTestsextensorHallucisRight: formValue.manual_muscle_testsextensor_hallucis_right || '',
      manualMuscleTestsextensorHallucisRightCustom: formValue.manual_muscle_testsextensor_hallucis_right_custom || '',
      manualMuscleTestsextensorHallucisLeft: formValue.manual_muscle_testsextensor_hallucis_left || '',
      manualMuscleTestsextensorHallucisLeftCustom: formValue.manual_muscle_testsextensor_hallucis_left_custom || '',
      manualMuscleTestsflexorHallucisRight: formValue.manual_muscle_testsflexor_hallucis_right || '',
      manualMuscleTestsflexorHallucisRightCustom: formValue.manual_muscle_testsflexor_hallucis_right_custom || '',
      manualMuscleTestsflexorHallucisLeft: formValue.manual_muscle_testsflexor_hallucis_left || '',
      manualMuscleTestsflexorHallucisLeftCustom: formValue.manual_muscle_testsflexor_hallucis_left_custom || '',
      manualMuscleTestsflexorDigitorumLongusRight: formValue.manual_muscle_testsflexor_digitorum_longus_right || '',
      manualMuscleTestsflexorDigitorumLongusRightCustom: formValue.manual_muscle_testsflexor_digitorum_longus_right_custom || '',
      manualMuscleTestsflexorDigitorumLongusLeft: formValue.manual_muscle_testsflexor_digitorum_longus_left || '',
      manualMuscleTestsflexorDigitorumLongusLeftCustom: formValue.manual_muscle_testsflexor_digitorum_longus_left_custom || '',
      manualMuscleTestsComments: formValue.manual_muscle_tests_comments || ''
    };

    const additionalComments: AdditionalComments = {
      additionalComments: formValue.additional_comments === 'yes',
      additionalCommentsText: formValue.additional_comments_text || ''
    };

    return {
      noLimitationsNoted,
      selectiveTissueTensionUpper,
      selectiveTissueTensionLower,
      gripPinch,
      grossMuscleTestsUpper,
      redcordNeuracStabilityTests,
      grossMuscleTestsTrunk,
      grossMuscleTestsLower,
      coreStrength,
      manualMuscleTests,
      additionalComments
    };
  }
}
