import { AdditionalComments } from "./AdditionalComments";
import { AlarLigamentStress } from "./AlarLigamentStress";
import { AlarLigamentTest } from "./AlarLigamentTest";
import { Flexibility } from "./Flexibility";
import { Functional } from "./Functional";
import { LigamentIntegrityKnee } from "./LigamentIntegrityKnee";
import { Patellofemoral } from "./Patellofemoral";
import { StorkStandSIMobilityTest } from "./StorkStandSIMobilityTest";
import { Structural } from "./Structural";
import { TMRFAB4Worksheet } from "./TMRFAB4Worksheet";
import { WorkConditioning } from "./WorkConditioning";
import { CervicalPassiveVertebralMobility } from "./CervicalPassiveVertebralMobility";
import { PassiveVertebralMobilityThoracic } from "./PassiveVertebralMobilityThoracic";
import { CervicalQuadrant } from "./CervicalQuadrant";
import { CervicalCompDist } from "./CervicalCompDist";
import { JawCrepitus } from "./JawCrepitus";
import { SpurlingsManeuver } from "./SpurlingsManeuver";
import { SubcranialPassiveVertebralMobility } from "./SubcranialPassiveVertebralMobility";
import { PassiveJointMobilityShoulder } from "./PassiveJointMobilityShoulder";
import { ScJoint } from "./ScJoint";
import { AcJoint } from "./AcJoint";
import { Impingement } from "./Impingement";
import { GhjStability } from "./GhjStability";
import { Labrum } from "./Labrum";
import { RotatorCuff } from "./RotatorCuff";
import { SpeedsTest } from "./SpeedsTest";
import { LigamentIntegrityElbow } from "./LigamentIntegrityElbow";
import { UlnarNerveSubluxation } from "./UlnarNerveSubluxation";
import { KempsTest } from "./KempsTest";
import { SiCompression } from "./SiCompression";
import { SiDistraction } from "./SiDistraction";
import { LegLength } from "./LegLength";
import { ProprioceptionBalance } from "./ProprioceptionBalance";
import { PelvicClock } from "./PelvicClock";
import { IntroitusClock } from "./IntroitusClock";
import { LaseguesSlr } from "./LaseguesSlr";

export interface SpecialTest {
  flexibility: Flexibility;
  structural: Structural;
  ligamentIntegrityKnee: LigamentIntegrityKnee;
  storkStandSIMobilityTest: StorkStandSIMobilityTest;
  patellofemoral: Patellofemoral;
  functional: Functional;
  alarLigamentTest: AlarLigamentTest;
  alarLigamentStress: AlarLigamentStress;
  workConditioning: WorkConditioning;
  tMRFAB4Worksheet: TMRFAB4Worksheet;
  cervicalPassiveVertebralMobility: CervicalPassiveVertebralMobility;
  passiveVertebralMobilityThoracic: PassiveVertebralMobilityThoracic;
  cervicalQuadrant: CervicalQuadrant;
  cervicalCompDist: CervicalCompDist;
  jawCrepitus: JawCrepitus;
  spurlingsManeuver: SpurlingsManeuver;
  subcranialPassiveVertebralMobility: SubcranialPassiveVertebralMobility;
  passiveJointMobilityShoulder: PassiveJointMobilityShoulder;
  scJoint: ScJoint;
  acJoint: AcJoint;
  impingement: Impingement;
  ghjStability: GhjStability;
  labrum: Labrum;
  rotatorCuff: RotatorCuff;
  speedsTest: SpeedsTest;
  ligamentIntegrityElbow: LigamentIntegrityElbow;
  ulnarNerveSubluxation: UlnarNerveSubluxation;
  kempsTest: KempsTest;
  siCompression: SiCompression;
  siDistraction: SiDistraction;
  legLength: LegLength;
  proprioceptionBalance: ProprioceptionBalance;
  pelvicClock: PelvicClock;
  introitusClock: IntroitusClock;
  laseguesSlr: LaseguesSlr;
  additionalComments: AdditionalComments;
}
