import { RomOption } from './rom-types';

export const ROM_TEST_OPTIONS: RomOption[] = [
  { value: 'wfl', label: 'WFL' },
  { value: 'limited', label: 'Limited' },
  { value: 'hypermobile', label: 'Hypermobile' }
];

export const CERVICAL_ROM_OPTIONS: RomOption[] = [
  { value: 'wfl', label: 'WFL' },
  { value: 'limited', label: 'Limited' }
];

export const APPLY_TO_ALL_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wfl', label: 'WFL' },
  { value: 'limited', label: 'Limited' }
];

export const FORWARD_BENDING_OPTIONS: RomOption[] = [
  { value: 'wfl', label: 'WFL' },
  { value: 'limited', label: 'Limited' },
  { value: 'painful', label: 'Painful' },
  { value: 'restricted', label: 'Restricted' }
];

export const ENDFEEL_OPTIONS: RomOption[] = [
  { value: 'soft', label: 'Soft' },
  { value: 'firm', label: 'Firm' },
  { value: 'hard', label: 'Hard' },
  { value: 'empty', label: 'Empty' },
  { value: 'custom', label: 'Custom' }
];


export const DEFAULT_APPLY_TO_ALL_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' }
]

// Cervical AROM
export const CERVICAL_AROM_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0' },
  { value: '5', label: '5' },
  { value: '10', label: '10' },
  { value: '15', label: '15' },
  { value: '20', label: '20' },
  { value: '25', label: '25' },
  { value: '30', label: '30' },
  { value: '35', label: '35' },
  { value: '40', label: '40' },
  { value: '45', label: '45' },
  { value: '50', label: '50' },
  { value: '55', label: '55' },
  { value: '60', label: '60' },
  { value: '65', label: '65' },
  { value: '70', label: '70' },
  { value: '75', label: '75' },
  { value: '80', label: '80' },
  { value: '85', label: '85' },
  { value: '90', label: '90' },
  { value: '100', label: '100' }
]
export const CERVICAL_AROM_SPECIAL_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0' },
  { value: '5', label: '5' },
  { value: '10', label: '10' },
  { value: '15', label: '15' },
  { value: '20', label: '20' },
  { value: '25', label: '25' },
  { value: '30', label: '30' },
  { value: '35', label: '35' },
  { value: '40', label: '40' },
  { value: '45', label: '45' },
  { value: '50', label: '50' },
  { value: '55', label: '55' },
  { value: '60', label: '60' },
  { value: '65', label: '65' },
  { value: '70', label: '70' },
  { value: '75', label: '75' },
  { value: '80', label: '80' },
  { value: '85', label: '85' },
  { value: '90', label: '90' },
  { value: '100', label: '100' },
  { value: 'b98', label: '3 Fingers From Chest' },
  { value: 'b99', label: '2 Fingers From Chest' },
  { value: 'b100', label: '1 Finger From Chest' },
  { value: 'b101', label: 'Chin To Chest' }
]

export const COSTOVERTEBRAL_EXPANSION_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '1.0', label: '1.0' },
  { value: '2.0', label: '2.0' },
  { value: '3.0', label: '3.0' },
  { value: '4.0', label: '4.0' },
  { value: '5.0', label: '5.0' },
  { value: '6.0', label: '6.0' },
  { value: '7.0', label: '7.0' },
  { value: '8.0', label: '8.0' },
  { value: '9.0', label: '9.0' },
  { value: '10.0', label: '10.0' }
]

export const LUMBAR_AROM_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0' },
  { value: '5', label: '5' },
  { value: '10', label: '10' },
  { value: '15', label: '15' },
  { value: '20', label: '20' },
  { value: '25', label: '25' },
  { value: '30', label: '30' },
  { value: '35', label: '35' },
  { value: '40', label: '40' },
  { value: '45', label: '45' },
  { value: '50', label: '50' },
  { value: '75', label: '75' },
  { value: '100', label: '100' }
]
export const LUMBAR_AROM_SPECIAL_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0' },
  { value: '5', label: '5' },
  { value: '10', label: '10' },
  { value: '15', label: '15' },
  { value: '20', label: '20' },
  { value: '25', label: '25' },
  { value: '30', label: '30' },
  { value: '35', label: '35' },
  { value: '40', label: '40' },
  { value: '45', label: '45' },
  { value: '50', label: '50' },
  { value: '75', label: '75' },
  { value: '100', label: '100' },
  { value: 'b98', label: '3 Fingers From Chest' },
  { value: 'b99', label: '2 Fingers From Chest' },
  { value: 'b100', label: '1 Finger From Chest' },
  { value: 'b101', label: 'Chin To Chest' }
]

export const THORACIC_AROM_SITTING_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0' },
  { value: '5', label: '5' },
  { value: '10', label: '10' },
  { value: '15', label: '15' },
  { value: '20', label: '20' },
  { value: '25', label: '25' },
  { value: '30', label: '30' },
  { value: '35', label: '35' },
  { value: '40', label: '40' },
  { value: '45', label: '45' },
  { value: '50', label: '50' },
  { value: '75', label: '75' },
  { value: '100', label: '100' }
]
export const THORACIC_AROM_STANDING_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0' },
  { value: '5', label: '5' },
  { value: '10', label: '10' },
  { value: '15', label: '15' },
  { value: '20', label: '20' },
  { value: '25', label: '25' },
  { value: '30', label: '30' },
  { value: '35', label: '35' },
  { value: '40', label: '40' },
  { value: '45', label: '45' },
  { value: '50', label: '50' },
  { value: '75', label: '75' },
  { value: '100', label: '100' }
]
export const SHOULDER_AROM_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '90', label: '90 °' },
  { value: '100', label: '100 °' },
  { value: '110', label: '110 °' },
  { value: '120', label: '120 °' },
  { value: '130', label: '130 °' },
  { value: '140', label: '140 °' },
  { value: '150', label: '150 °' },
  { value: '160', label: '160 °' },
  { value: '170', label: '170 °' },
  { value: '180', label: '180 °' }
]
export const SHOULDER_AROM_Extension_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '20', label: '20 °' },
  { value: '20', label: '20 °' },
  { value: '30', label: '30 °' },
  { value: '40', label: '40 °' },
  { value: '50', label: '50 °' },
  { value: '60', label: '60 °' },
  { value: '70', label: '70 °' },
  { value: '80', label: '80 °' }
]
export const SHOULDER_AROM_External_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'to_opp_side', label: '= to opp side' },
  { value: 'xheek', label: 'Cheek' },
  { value: 'custom', label: 'Custom' },
  { value: 'ear', label: 'Ear' },
  { value: 'subcranial', label: 'Subcranial' },
  { value: 'C3', label: 'C3' },
  { value: 'C4', label: 'C4' },
  { value: 'C5', label: 'C5' },
  { value: 'C6', label: 'C6' },
  { value: 'C7', label: 'C7' },
  { value: 'T1', label: 'T1' },
  { value: 'T2', label: 'T2' },
  { value: 'T3', label: 'T3' },
  { value: 'T4', label: 'T4' },
  { value: 'T5', label: 'T5' }
]
export const SHOULDER_AROM_INTERNAL_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'to_opp_side', label: '= to opp side' },
  { value: 'iliac_crest', label: 'Iliac Crest' },
  { value: 'custom', label: 'Custom' },
  { value: 'gluteals', label: 'Gluteals' },
  { value: 'PSIS', label: 'PSIS' },
  { value: 'sacrum', label: 'Sacrum' },
  { value: 'L5', label: 'L5' },
  { value: 'L4', label: 'L4' },
  { value: 'L3', label: 'L3' },
  { value: 'L2', label: 'L2' },
  { value: 'L1', label: 'L1' },
  { value: 'T12', label: 'T12' },
  { value: 'T11', label: 'T11' },
  { value: 'T10', label: 'T10' },
  { value: 'T9', label: 'T9' },
  { value: 'T8', label: 'T8' },
  { value: 'T7', label: 'T7' },
  { value: 'T6', label: 'T6' },
  { value: 'T5_or_greater', label: 'T5 or >' }
]
export const SHOULDER_AROM_POSITION_ABDUCTION_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0 °' },
  { value: '10', label: '10 °' },
  { value: '20', label: '20 °' },
  { value: '30', label: '30 °' },
  { value: '40', label: '40 °' },
  { value: '45', label: '45 °' },
  { value: '50', label: '50 °' },
  { value: '55', label: '55 °' },
  { value: '60', label: '60 °' },
  { value: '65', label: '65 °' },
  { value: '70', label: '70 °' },
  { value: '75', label: '75 °' },
  { value: '80', label: '80 °' },
  { value: '85', label: '85 °' },
  { value: '90', label: '90 °' },
  { value: '95', label: '95 °' },
  { value: '100', label: '100 °' }
]

export const ALBOW_AROM_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '30', label: '(30) °' },
  { value: '25', label: '(25) °' },
  { value: '20', label: '(20) °' },
  { value: '15', label: '(15) °' },
  { value: '10', label: '(10) °' },
  { value: '5', label: '(5) °' },
  { value: '0', label: '0 °' },
  { value: '1_Hyperextension', label: '1 ° Hyperextension' },
  { value: '2_Hyperextension', label: '2 ° Hyperextension' },
  { value: '3_Hyperextension', label: '3 ° Hyperextension' },
  { value: '4_Hyperextension', label: '4 ° Hyperextension' },
  { value: '5_Hyperextension', label: '5 ° Hyperextension' },
  { value: '6_Hyperextension', label: '6 ° Hyperextension' },
  { value: '7_Hyperextension', label: '7 ° Hyperextension' },
  { value: '8_Hyperextension', label: '8 ° Hyperextension' },
  { value: '9_Hyperextension', label: '9 ° Hyperextension' },
  { value: '10_Hyperextension', label: '10 ° Hyperextension' },
  { value: '11_Hyperextension', label: '11 ° Hyperextension' },
  { value: '12_Hyperextension', label: '12 ° Hyperextension' },
  { value: '13_Hyperextension', label: '13 ° Hyperextension' },
  { value: '14_Hyperextension', label: '14 ° Hyperextension' },
  { value: '15_Hyperextension', label: '15 ° Hyperextension' }
]
export const ALBOW_AROM_FLEXION_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0 °' },
  { value: '10', label: '10 °' },
  { value: '20', label: '20 °' },
  { value: '30', label: '30 °' },
  { value: '40', label: '40 °' },
  { value: '50', label: '50 °' },
  { value: '60', label: '60 °' },
  { value: '80', label: '80 °' },
  { value: '90', label: '90 °' },
  { value: '95', label: '95 °' },
  { value: '100', label: '100 °' },
  { value: '105', label: '105 °' },
  { value: '110', label: '110 °' },
  { value: '115', label: '115 °' },
  { value: '120', label: '120 °' },
  { value: '125', label: '125 °' },
  { value: '130', label: '130 °' },
  { value: '135', label: '135 °' },
  { value: '140', label: '140 °' },
  { value: '145', label: '145 °' },
  { value: '150', label: '150 °' }
]
export const ALBOW_AROM_SUPINATION_PRONATION_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0 °' },
  { value: '5', label: '5 °' },
  { value: '10', label: '10 °' },
  { value: '15', label: '15 °' },
  { value: '20', label: '20 °' },
  { value: '25', label: '25 °' },
  { value: '30', label: '30 °' },
  { value: '35', label: '35 °' },
  { value: '40', label: '40 °' },
  { value: '45', label: '45 °' },
  { value: '50', label: '50 °' },
  { value: '55', label: '55 °' },
  { value: '60', label: '60 °' },
  { value: '65', label: '65 °' },
  { value: '70', label: '70 °' },
  { value: '75', label: '75 °' },
  { value: '80', label: '80 °' },
  { value: '85', label: '85 °' },
  { value: '90', label: '90 °' }
]

export const WRIST_AROM_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '30', label: '(30) °' },
  { value: '25', label: '(25) °' },
  { value: '20', label: '(20) °' },
  { value: '15', label: '(15) °' },
  { value: '10', label: '(10) °' },
  { value: '5', label: '(5) °' },
  { value: '0', label: '0 °' },
  { value: '1_Hyperextension', label: '1 ° Hyperextension' },
  { value: '2_Hyperextension', label: '2 ° Hyperextension' },
  { value: '3_Hyperextension', label: '3 ° Hyperextension' },
  { value: '4_Hyperextension', label: '4 ° Hyperextension' },
  { value: '5_Hyperextension', label: '5 ° Hyperextension' },
  { value: '6_Hyperextension', label: '6 ° Hyperextension' },
  { value: '7_Hyperextension', label: '7 ° Hyperextension' },
  { value: '8_Hyperextension', label: '8 ° Hyperextension' },
  { value: '9_Hyperextension', label: '9 ° Hyperextension' },
  { value: '10_Hyperextension', label: '10 ° Hyperextension' },
  { value: '11_Hyperextension', label: '11 ° Hyperextension' },
  { value: '12_Hyperextension', label: '12 ° Hyperextension' },
  { value: '13_Hyperextension', label: '13 ° Hyperextension' },
  { value: '14_Hyperextension', label: '14 ° Hyperextension' },
  { value: '15_Hyperextension', label: '15 ° Hyperextension' }
]
export const WRIST_AROM_FLEXION_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0 °' },
  { value: '10', label: '10 °' },
  { value: '20', label: '20 °' },
  { value: '30', label: '30 °' },
  { value: '40', label: '40 °' },
  { value: '50', label: '50 °' },
  { value: '60', label: '60 °' },
  { value: '80', label: '80 °' },
  { value: '90', label: '90 °' },
  { value: '95', label: '95 °' },
  { value: '100', label: '100 °' },
  { value: '105', label: '105 °' },
  { value: '110', label: '110 °' },
  { value: '115', label: '115 °' },
  { value: '120', label: '120 °' },
  { value: '125', label: '125 °' },
  { value: '130', label: '130 °' },
  { value: '135', label: '135 °' },
  { value: '140', label: '140 °' },
  { value: '145', label: '145 °' },
  { value: '150', label: '150 °' }
]
export const WRIST_AROM_SUPINATION_PRONATION_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0 °' },
  { value: '5', label: '5 °' },
  { value: '10', label: '10 °' },
  { value: '15', label: '15 °' },
  { value: '20', label: '20 °' },
  { value: '25', label: '25 °' },
  { value: '30', label: '30 °' },
  { value: '35', label: '35 °' },
  { value: '40', label: '40 °' },
  { value: '45', label: '45 °' },
  { value: '50', label: '50 °' },
  { value: '55', label: '55 °' },
  { value: '60', label: '60 °' },
  { value: '65', label: '65 °' },
  { value: '70', label: '70 °' },
  { value: '75', label: '75 °' },
  { value: '80', label: '80 °' },
  { value: '85', label: '85 °' },
  { value: '90', label: '90 °' }
]
export const HIP_AROM_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0 °' },
  { value: '5', label: '5 °' },
  { value: '10', label: '10 °' },
  { value: '15', label: '15 °' },
  { value: '20', label: '20 °' },
  { value: '25', label: '25 °' },
  { value: '30', label: '30 °' },
  { value: '35', label: '35 °' },
  { value: '40', label: '40 °' },
  { value: '45', label: '45 °' },
  { value: '50', label: '50 °' },
  { value: '55', label: '55 °' },
  { value: '60', label: '60 °' },
  { value: '65', label: '65 °' },
  { value: '70', label: '70 °' },
  { value: '80', label: '80 °' },
  { value: '85', label: '85 °' },
  { value: '85', label: '85 °' }
]
export const HIP_AROM_FLEXION_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '130', label: '130 °' },
  { value: '125', label: '125 °' },
  { value: '120', label: '120 °' },
  { value: '115', label: '115 °' },
  { value: '110', label: '110 °' },
  { value: '105', label: '105 °' },
  { value: '100', label: '100 °' },
  { value: '95', label: '95 °' },
  { value: '90', label: '90 °' },
  { value: '85', label: '85 °' },
  { value: '80', label: '80 °' },
  { value: '60', label: '60 °' },
  { value: '40', label: '40 °' },
  { value: '40', label: '40 °' },
  { value: '0', label: '0 °' }
]
export const HIP_AROM_EXTENSION_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '30', label: '(30) °' },
  { value: '25', label: '(25) °' },
  { value: '20', label: '(20) °' },
  { value: '15', label: '(15) °' },
  { value: '10', label: '(10) °' },
  { value: '5', label: '(5) °' },
  { value: '0', label: '0 °' },
  { value: '5', label: '5 °' },
  { value: '10', label: '10 °' },
  { value: '15', label: '15 °' },
  { value: '20', label: '20 °' },
  { value: '25', label: '25 °' },
  { value: '30', label: '30 °' }
]
export const HIP_AROM_ABDUCTION_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '(10) °', label: '(10) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' },
  { value: '55 °', label: '55 °' },
  { value: '60 °', label: '60 °' },
  { value: '65 °', label: '65 °' },
  { value: '70 °', label: '70 °' },
  { value: '75 °', label: '75 °' },
  { value: '80 °', label: '80 °' },
  { value: '85 °', label: '85 °' },
  { value: '90 °', label: '90 °' }
]
export const HIP_AROM_ADDUCTION_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '(10) °', label: '(10) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' }
]

export const SND_MTP_FLEXION_OPTION: RomOption[] = [{ value: 'Not Tested', label: 'Not Tested' },
{ value: 'not_tested', label: 'Not Tested' },
{ value: 'wnl', label: 'WNL' },
{ value: 'wfl', label: 'WFL' },
{ value: 'Custom', label: 'Custom' },
{ value: '(30) °', label: '(30) °' },
{ value: '(25) °', label: '(25) °' },
{ value: '(20) °', label: '(20) °' },
{ value: '(15) °', label: '(15) °' },
{ value: '(10) °', label: '(10) °' },
{ value: '(5) °', label: '(5) °' },
{ value: '0 °', label: '0 °' },
{ value: '5 °', label: '5 °' },
{ value: '10 °', label: '10 °' },
{ value: '15 °', label: '15 °' },
{ value: '20 °', label: '20 °' },
{ value: '25 °', label: '25 °' },
{ value: '30 °', label: '30 °' },
{ value: '35 °', label: '35 °' },
{ value: '40 °', label: '40 °' },
{ value: '45 °', label: '45 °' },
{ value: '50 °', label: '50 °' },
{ value: '55 °', label: '55 °' },
{ value: '60 °', label: '60 °' },
{ value: '65 °', label: '65 °' },
{ value: '70 °', label: '70 °' },
{ value: '75 °', label: '75 °' }]

export const SND_MTP_EXTENSION_OPTION: RomOption[] = [{ value: 'Not Tested', label: 'Not Tested' },
{ value: 'not_tested', label: 'Not Tested' },
{ value: 'wnl', label: 'WNL' },
{ value: 'wfl', label: 'WFL' },
{ value: 'Custom', label: 'Custom' },
{ value: '(30) °', label: '(30) °' },
{ value: '(25) °', label: '(25) °' },
{ value: '(20) °', label: '(20) °' },
{ value: '(15) °', label: '(15) °' },
{ value: '(10) °', label: '(10) °' },
{ value: '(5) °', label: '(5) °' },
{ value: '0 °', label: '0 °' },
{ value: '5 °', label: '5 °' },
{ value: '10 °', label: '10 °' },
{ value: '15 °', label: '15 °' },
{ value: '20 °', label: '20 °' },
{ value: '25 °', label: '25 °' },
{ value: '30 °', label: '30 °' },
{ value: '35 °', label: '35 °' },
{ value: '40 °', label: '40 °' }]

export const SND_IP_FLEXION_OPTION: RomOption[] = [{ value: 'Not Tested', label: 'Not Tested' },
{ value: 'not_tested', label: 'Not Tested' },
{ value: 'wnl', label: 'WNL' },
{ value: 'wfl', label: 'WFL' },
{ value: 'Custom', label: 'Custom' },
{ value: '(30) °', label: '(30) °' },
{ value: '(25) °', label: '(25) °' },
{ value: '(20) °', label: '(20) °' },
{ value: '(15) °', label: '(15) °' },
{ value: '(10) °', label: '(10) °' },
{ value: '(5) °', label: '(5) °' },
{ value: '0 °', label: '0 °' },
{ value: '5 °', label: '5 °' },
{ value: '10 °', label: '10 °' },
{ value: '15 °', label: '15 °' },
{ value: '20 °', label: '20 °' },
{ value: '25 °', label: '25 °' },
{ value: '30 °', label: '30 °' },
{ value: '35 °', label: '35 °' },
{ value: '40 °', label: '40 °' },
{ value: '45 °', label: '45 °' },
{ value: '50 °', label: '50 °' },
{ value: '55 °', label: '55 °' },
{ value: '60 °', label: '60 °' },
{ value: '65 °', label: '65 °' },
{ value: '70 °', label: '70 °' },
{ value: '75 °', label: '75 °' }]

export const SND_IP_EXTENSION_OPTION: RomOption[] = [{ value: 'Not Tested', label: 'Not Tested' },
{ value: 'not_tested', label: 'Not Tested' },
{ value: 'wnl', label: 'WNL' },
{ value: 'wfl', label: 'WFL' },
{ value: 'Custom', label: 'Custom' },
{ value: '(30) °', label: '(30) °' },
{ value: '(25) °', label: '(25) °' },
{ value: '(20) °', label: '(20) °' },
{ value: '(15) °', label: '(15) °' },
{ value: '(10) °', label: '(10) °' },
{ value: '(5) °', label: '(5) °' },
{ value: '0 °', label: '0 °' },
{ value: '5 °', label: '5 °' },
{ value: '10 °', label: '10 °' },
{ value: '15 °', label: '15 °' },
{ value: '20 °', label: '20 °' },
{ value: '25 °', label: '25 °' },
{ value: '30 °', label: '30 °' },
{ value: '35 °', label: '35 °' },
{ value: '40 °', label: '40 °' }]

export const TRD_MTP_FLEXION_OPTION: RomOption[] = [{ value: 'Not Tested', label: 'Not Tested' },
{ value: 'not_tested', label: 'Not Tested' },
{ value: 'wnl', label: 'WNL' },
{ value: 'wfl', label: 'WFL' },
{ value: 'Custom', label: 'Custom' },
{ value: '(30) °', label: '(30) °' },
{ value: '(25) °', label: '(25) °' },
{ value: '(20) °', label: '(20) °' },
{ value: '(15) °', label: '(15) °' },
{ value: '(10) °', label: '(10) °' },
{ value: '(5) °', label: '(5) °' },
{ value: '0 °', label: '0 °' },
{ value: '5 °', label: '5 °' },
{ value: '10 °', label: '10 °' },
{ value: '15 °', label: '15 °' },
{ value: '20 °', label: '20 °' },
{ value: '25 °', label: '25 °' },
{ value: '30 °', label: '30 °' },
{ value: '35 °', label: '35 °' },
{ value: '40 °', label: '40 °' },
{ value: '45 °', label: '45 °' },
{ value: '50 °', label: '50 °' },
{ value: '55 °', label: '55 °' },
{ value: '60 °', label: '60 °' },
{ value: '65 °', label: '65 °' },
{ value: '70 °', label: '70 °' },
{ value: '75 °', label: '75 °' }]

export const TRD_MTP_EXTENSION_OPTION: RomOption[] = [{ value: 'Not Tested', label: 'Not Tested' },
{ value: 'not_tested', label: 'Not Tested' },
{ value: 'wnl', label: 'WNL' },
{ value: 'wfl', label: 'WFL' },
{ value: 'Custom', label: 'Custom' },
{ value: '(30) °', label: '(30) °' },
{ value: '(25) °', label: '(25) °' },
{ value: '(20) °', label: '(20) °' },
{ value: '(15) °', label: '(15) °' },
{ value: '(10) °', label: '(10) °' },
{ value: '(5) °', label: '(5) °' },
{ value: '0 °', label: '0 °' },
{ value: '5 °', label: '5 °' },
{ value: '10 °', label: '10 °' },
{ value: '15 °', label: '15 °' },
{ value: '20 °', label: '20 °' },
{ value: '25 °', label: '25 °' },
{ value: '30 °', label: '30 °' },
{ value: '35 °', label: '35 °' },
{ value: '40 °', label: '40 °' }]

export const TRD_IP_FLEXION_OPTION: RomOption[] = [{ value: 'Not Tested', label: 'Not Tested' },
{ value: 'not_tested', label: 'Not Tested' },
{ value: 'wnl', label: 'WNL' },
{ value: 'wfl', label: 'WFL' },
{ value: 'Custom', label: 'Custom' },
{ value: '(30) °', label: '(30) °' },
{ value: '(25) °', label: '(25) °' },
{ value: '(20) °', label: '(20) °' },
{ value: '(15) °', label: '(15) °' },
{ value: '(10) °', label: '(10) °' },
{ value: '(5) °', label: '(5) °' },
{ value: '0 °', label: '0 °' },
{ value: '5 °', label: '5 °' },
{ value: '10 °', label: '10 °' },
{ value: '15 °', label: '15 °' },
{ value: '20 °', label: '20 °' },
{ value: '25 °', label: '25 °' },
{ value: '30 °', label: '30 °' },
{ value: '35 °', label: '35 °' },
{ value: '40 °', label: '40 °' },
{ value: '45 °', label: '45 °' },
{ value: '50 °', label: '50 °' },
{ value: '55 °', label: '55 °' },
{ value: '60 °', label: '60 °' },
{ value: '65 °', label: '65 °' },
{ value: '70 °', label: '70 °' },
{ value: '75 °', label: '75 °' }]

export const TRD_IP_EXTENSION_OPTION: RomOption[] = [{ value: 'Not Tested', label: 'Not Tested' },
{ value: 'not_tested', label: 'Not Tested' },
{ value: 'wnl', label: 'WNL' },
{ value: 'wfl', label: 'WFL' },
{ value: 'Custom', label: 'Custom' },
{ value: '(30) °', label: '(30) °' },
{ value: '(25) °', label: '(25) °' },
{ value: '(20) °', label: '(20) °' },
{ value: '(15) °', label: '(15) °' },
{ value: '(10) °', label: '(10) °' },
{ value: '(5) °', label: '(5) °' },
{ value: '0 °', label: '0 °' },
{ value: '5 °', label: '5 °' },
{ value: '10 °', label: '10 °' },
{ value: '15 °', label: '15 °' },
{ value: '20 °', label: '20 °' },
{ value: '25 °', label: '25 °' },
{ value: '30 °', label: '30 °' },
{ value: '35 °', label: '35 °' },
{ value: '40 °', label: '40 °' }]

export const FRTH_MTP_FLEXION_OPTION: RomOption[] = [{ value: 'Not Tested', label: 'Not Tested' },
{ value: 'not_tested', label: 'Not Tested' },
{ value: 'wnl', label: 'WNL' },
{ value: 'wfl', label: 'WFL' },
{ value: 'Custom', label: 'Custom' },
{ value: '(30) °', label: '(30) °' },
{ value: '(25) °', label: '(25) °' },
{ value: '(20) °', label: '(20) °' },
{ value: '(15) °', label: '(15) °' },
{ value: '(10) °', label: '(10) °' },
{ value: '(5) °', label: '(5) °' },
{ value: '0 °', label: '0 °' },
{ value: '5 °', label: '5 °' },
{ value: '10 °', label: '10 °' },
{ value: '15 °', label: '15 °' },
{ value: '20 °', label: '20 °' },
{ value: '25 °', label: '25 °' },
{ value: '30 °', label: '30 °' },
{ value: '35 °', label: '35 °' },
{ value: '40 °', label: '40 °' },
{ value: '45 °', label: '45 °' },
{ value: '50 °', label: '50 °' },
{ value: '55 °', label: '55 °' },
{ value: '60 °', label: '60 °' },
{ value: '65 °', label: '65 °' },
{ value: '70 °', label: '70 °' },
{ value: '75 °', label: '75 °' }]

export const FRTH_MTP_EXTENSION_OPTION: RomOption[] = [{ value: 'Not Tested', label: 'Not Tested' },
{ value: 'not_tested', label: 'Not Tested' },
{ value: 'wnl', label: 'WNL' },
{ value: 'wfl', label: 'WFL' },
{ value: 'Custom', label: 'Custom' },
{ value: '(30) °', label: '(30) °' },
{ value: '(25) °', label: '(25) °' },
{ value: '(20) °', label: '(20) °' },
{ value: '(15) °', label: '(15) °' },
{ value: '(10) °', label: '(10) °' },
{ value: '(5) °', label: '(5) °' },
{ value: '0 °', label: '0 °' },
{ value: '5 °', label: '5 °' },
{ value: '10 °', label: '10 °' },
{ value: '15 °', label: '15 °' },
{ value: '20 °', label: '20 °' },
{ value: '25 °', label: '25 °' },
{ value: '30 °', label: '30 °' },
{ value: '35 °', label: '35 °' },
{ value: '40 °', label: '40 °' }]

export const FRTH_IP_FEXION_OPTION: RomOption[] = [{ value: 'Not Tested', label: 'Not Tested' },
{ value: 'not_tested', label: 'Not Tested' },
{ value: 'wnl', label: 'WNL' },
{ value: 'wfl', label: 'WFL' },
{ value: 'Custom', label: 'Custom' },
{ value: '(30) °', label: '(30) °' },
{ value: '(25) °', label: '(25) °' },
{ value: '(20) °', label: '(20) °' },
{ value: '(15) °', label: '(15) °' },
{ value: '(10) °', label: '(10) °' },
{ value: '(5) °', label: '(5) °' },
{ value: '0 °', label: '0 °' },
{ value: '5 °', label: '5 °' },
{ value: '10 °', label: '10 °' },
{ value: '15 °', label: '15 °' },
{ value: '20 °', label: '20 °' },
{ value: '25 °', label: '25 °' },
{ value: '30 °', label: '30 °' },
{ value: '35 °', label: '35 °' },
{ value: '40 °', label: '40 °' },
{ value: '45 °', label: '45 °' },
{ value: '50 °', label: '50 °' },
{ value: '55 °', label: '55 °' },
{ value: '60 °', label: '60 °' },
{ value: '65 °', label: '65 °' },
{ value: '70 °', label: '70 °' },
{ value: '75 °', label: '75 °' }]

export const FRTH_IP_EXTENSION_OPTION: RomOption[] = [{ value: 'Not Tested', label: 'Not Tested' },
{ value: 'not_tested', label: 'Not Tested' },
{ value: 'wnl', label: 'WNL' },
{ value: 'wfl', label: 'WFL' },
{ value: 'Custom', label: 'Custom' },
{ value: '(30) °', label: '(30) °' },
{ value: '(25) °', label: '(25) °' },
{ value: '(20) °', label: '(20) °' },
{ value: '(15) °', label: '(15) °' },
{ value: '(10) °', label: '(10) °' },
{ value: '(5) °', label: '(5) °' },
{ value: '0 °', label: '0 °' },
{ value: '5 °', label: '5 °' },
{ value: '10 °', label: '10 °' },
{ value: '15 °', label: '15 °' },
{ value: '20 °', label: '20 °' },
{ value: '25 °', label: '25 °' },
{ value: '30 °', label: '30 °' },
{ value: '35 °', label: '35 °' },
{ value: '40 °', label: '40 °' }]

export const FTH_MTP_FLEXION_OPTION: RomOption[] = [{ value: 'Not Tested', label: 'Not Tested' },
{ value: 'not_tested', label: 'Not Tested' },
{ value: 'wnl', label: 'WNL' },
{ value: 'wfl', label: 'WFL' },
{ value: 'Custom', label: 'Custom' },
{ value: '(30) °', label: '(30) °' },
{ value: '(25) °', label: '(25) °' },
{ value: '(20) °', label: '(20) °' },
{ value: '(15) °', label: '(15) °' },
{ value: '(10) °', label: '(10) °' },
{ value: '(5) °', label: '(5) °' },
{ value: '0 °', label: '0 °' },
{ value: '5 °', label: '5 °' },
{ value: '10 °', label: '10 °' },
{ value: '15 °', label: '15 °' },
{ value: '20 °', label: '20 °' },
{ value: '25 °', label: '25 °' },
{ value: '30 °', label: '30 °' },
{ value: '35 °', label: '35 °' },
{ value: '40 °', label: '40 °' },
{ value: '45 °', label: '45 °' },
{ value: '50 °', label: '50 °' },
{ value: '55 °', label: '55 °' },
{ value: '60 °', label: '60 °' },
{ value: '65 °', label: '65 °' },
{ value: '70 °', label: '70 °' },
{ value: '75 °', label: '75 °' }]

export const FTH_MTP_EXTENSION_OPTION: RomOption[] = [{ value: 'Not Tested', label: 'Not Tested' },
{ value: 'not_tested', label: 'Not Tested' },
{ value: 'wnl', label: 'WNL' },
{ value: 'wfl', label: 'WFL' },
{ value: 'Custom', label: 'Custom' },
{ value: '(30) °', label: '(30) °' },
{ value: '(25) °', label: '(25) °' },
{ value: '(20) °', label: '(20) °' },
{ value: '(15) °', label: '(15) °' },
{ value: '(10) °', label: '(10) °' },
{ value: '(5) °', label: '(5) °' },
{ value: '0 °', label: '0 °' },
{ value: '5 °', label: '5 °' },
{ value: '10 °', label: '10 °' },
{ value: '15 °', label: '15 °' },
{ value: '20 °', label: '20 °' },
{ value: '25 °', label: '25 °' },
{ value: '30 °', label: '30 °' },
{ value: '35 °', label: '35 °' },
{ value: '40 °', label: '40 °' }]

export const FTH_IP_FLEXION_OPTION: RomOption[] = [{ value: 'Not Tested', label: 'Not Tested' },
{ value: 'not_tested', label: 'Not Tested' },
{ value: 'wnl', label: 'WNL' },
{ value: 'wfl', label: 'WFL' },
{ value: 'Custom', label: 'Custom' },
{ value: '(30) °', label: '(30) °' },
{ value: '(25) °', label: '(25) °' },
{ value: '(20) °', label: '(20) °' },
{ value: '(15) °', label: '(15) °' },
{ value: '(10) °', label: '(10) °' },
{ value: '(5) °', label: '(5) °' },
{ value: '0 °', label: '0 °' },
{ value: '5 °', label: '5 °' },
{ value: '10 °', label: '10 °' },
{ value: '15 °', label: '15 °' },
{ value: '20 °', label: '20 °' },
{ value: '25 °', label: '25 °' },
{ value: '30 °', label: '30 °' },
{ value: '35 °', label: '35 °' },
{ value: '40 °', label: '40 °' },
{ value: '45 °', label: '45 °' },
{ value: '50 °', label: '50 °' },
{ value: '55 °', label: '55 °' },
{ value: '60 °', label: '60 °' },
{ value: '65 °', label: '65 °' },
{ value: '70 °', label: '70 °' },
{ value: '75 °', label: '75 °' }]

export const FTH_IP_EXTENSION_OPTION: RomOption[] = [
  { value: 'Not Tested', label: 'Not Tested' },
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '(30) °', label: '(30) °' },
  { value: '(25) °', label: '(25) °' },
  { value: '(20) °', label: '(20) °' },
  { value: '(15) °', label: '(15) °' },
  { value: '(10) °', label: '(10) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' }
]
export const KNEE_AROM_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '150 °', label: '150 °' },
  { value: '145 °', label: '145 °' },
  { value: '140 °', label: '140 °' },
  { value: '135 °', label: '135 °' },
  { value: '130 °', label: '130 °' },
  { value: '125 °', label: '125 °' },
  { value: '120 °', label: '120 °' },
  { value: '115 °', label: '115 °' },
  { value: '110 °', label: '110 °' },
  { value: '105 °', label: '105 °' },
  { value: '100 °', label: '100 °' },
  { value: '95 °', label: '95 °' },
  { value: '90 °', label: '90 °' },
  { value: '85 °', label: '85 °' },
  { value: '80 °', label: '80 °' },
  { value: '75 °', label: '75 °' },
  { value: '70 °', label: '70 °' },
  { value: '65 °', label: '65 °' },
  { value: '60 °', label: '60 °' },
  { value: '55 °', label: '55 °' },
  { value: '50 °', label: '50 °' },
  { value: '40 °', label: '40 °' },
  { value: '30 °', label: '30 °' },
  { value: '20 °', label: '20 °' },
  { value: '10 °', label: '10 °' },
  { value: '0 °', label: '0 °' }
]
export const KNEE_AROM_EXTENSION_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '(30) °', label: '(30) °' },
  { value: '(25) °', label: '(25) °' },
  { value: '(20) °', label: '(20) °' },
  { value: '(15) °', label: '(15) °' },
  { value: '(10) °', label: '(10) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '0 °', label: '0 °' },
  { value: '1 ° Hyperextension', label: '1 ° Hyperextension' },
  { value: '2 ° Hyperextension', label: '2 ° Hyperextension' },
  { value: '3 ° Hyperextension', label: '3 ° Hyperextension' },
  { value: '4 ° Hyperextension', label: '4 ° Hyperextension' },
  { value: '5 ° Hyperextension', label: '5 ° Hyperextension' },
  { value: '6 ° Hyperextension', label: '6 ° Hyperextension' },
  { value: '7 ° Hyperextension', label: '7 ° Hyperextension' },
  { value: '8 ° Hyperextension', label: '8 ° Hyperextension' },
  { value: '9 ° Hyperextension', label: '9 ° Hyperextension' },
  { value: '10 ° Hyperextension', label: '10 ° Hyperextension' },
  { value: '11 ° Hyperextension', label: '11 ° Hyperextension' },
  { value: '12 ° Hyperextension', label: '12 ° Hyperextension' },
  { value: '13 ° Hyperextension', label: '13 ° Hyperextension' },
  { value: '14 ° Hyperextension', label: '14 ° Hyperextension' },
  { value: '15 ° Hyperextension', label: '15 ° Hyperextension' }
]

export const DORSIFLEXION_AT_0_ANKLE_AROM_FLEXION_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '(30) °', label: '(30) °' },
  { value: '(25) °', label: '(25) °' },
  { value: '(20) °', label: '(20) °' },
  { value: '(15) °', label: '(15) °' },
  { value: '(10) °', label: '(10) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' }
]

export const DORSIFLEXION_AT_90_ANKLE_AROM_FLEXION_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '(30) °', label: '(30) °' },
  { value: '(25) °', label: '(25) °' },
  { value: '(20) °', label: '(20) °' },
  { value: '(15) °', label: '(15) °' },
  { value: '(10) °', label: '(10) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' }
]
export const PLANTARFLEXION_ANKLE_AROM_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' },
  { value: '55 °', label: '55 °' },
  { value: '60 °', label: '60 °' },
  { value: '65 °', label: '65 °' },
  { value: '70 °', label: '70 °' }
]

export const INVERSION_ANKLE_AROM_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '(10) °', label: '(10) °' },
  { value: '(8) °', label: '(8) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '(3) °', label: '(3) °' },
  { value: '0 °', label: '0 °' },
  { value: '2 °', label: '2 °' },
  { value: '4 °', label: '4 °' },
  { value: '6 °', label: '6 °' },
  { value: '8 °', label: '8 °' },
  { value: '10 °', label: '10 °' },
  { value: '12 °', label: '12 °' },
  { value: '14 °', label: '14 °' },
  { value: '16 °', label: '16 °' },
  { value: '18 °', label: '18 °' },
  { value: '20 °', label: '20 °' },
  { value: '22 °', label: '22 °' },
  { value: '24 °', label: '24 °' },
  { value: '26 °', label: '26 °' },
  { value: '28 °', label: '28 °' },
  { value: '30 °', label: '30 °' }
]
export const EVERSION_ANKLE_AROM_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '(10) °', label: '(10) °' },
  { value: '(8) °', label: '(8) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '(3) °', label: '(3) °' },
  { value: '0 °', label: '0 °' },
  { value: '2 °', label: '2 °' },
  { value: '4 °', label: '4 °' },
  { value: '6 °', label: '6 °' },
  { value: '8 °', label: '8 °' },
  { value: '10 °', label: '10 °' },
  { value: '12 °', label: '12 °' },
  { value: '14 °', label: '14 °' },
  { value: '16 °', label: '16 °' },
  { value: '18 °', label: '18 °' },
  { value: '20 °', label: '20 °' }
]

export const FLEXION_FST_MTP_AROM_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '(30) °', label: '(30) °' },
  { value: '(25) °', label: '(25) °' },
  { value: '(20) °', label: '(20) °' },
  { value: '(15) °', label: '(15) °' },
  { value: '(10) °', label: '(10) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' },
  { value: '55 °', label: '55 °' },
  { value: '60 °', label: '60 °' },
  { value: '65 °', label: '65 °' },
  { value: '70 °', label: '70 °' },
  { value: '75 °', label: '75 °' }
]

export const EXTENSION_FST_MTP_AROM_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '(30) °', label: '(30) °' },
  { value: '(25) °', label: '(25) °' },
  { value: '(20) °', label: '(20) °' },
  { value: '(15) °', label: '(15) °' },
  { value: '(10) °', label: '(10) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' },
  { value: '55 °', label: '55 °' },
  { value: '60 °', label: '60 °' },
  { value: '65 °', label: '65 °' },
  { value: '70 °', label: '70 °' },
  { value: '75 °', label: '75 °' },
  { value: '80 °', label: '80 °' },
  { value: '85 °', label: '85 °' },
  { value: '90 °', label: '90 °' }
]



export const FLEXION_FST_IP_AROM_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '(30) °', label: '(30) °' },
  { value: '(25) °', label: '(25) °' },
  { value: '(20) °', label: '(20) °' },
  { value: '(15) °', label: '(15) °' },
  { value: '(10) °', label: '(10) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' },
  { value: '55 °', label: '55 °' },
  { value: '60 °', label: '60 °' },
  { value: '65 °', label: '65 °' },
  { value: '70 °', label: '70 °' },
  { value: '75 °', label: '75 °' }
]

export const EXTENSION_FST_IP_AROM_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '(30) °', label: '(30) °' },
  { value: '(25) °', label: '(25) °' },
  { value: '(20) °', label: '(20) °' },
  { value: '(15) °', label: '(15) °' },
  { value: '(10) °', label: '(10) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' },
  { value: '55 °', label: '55 °' },
  { value: '60 °', label: '60 °' },
  { value: '65 °', label: '65 °' },
  { value: '70 °', label: '70 °' },
  { value: '75 °', label: '75 °' },
  { value: '80 °', label: '80 °' },
  { value: '85 °', label: '85 °' },
  { value: '90 °', label: '90 °' }
]


export const SHOULDER_PROM_180_OPTION: RomOption[] = [

  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '90 °', label: '90 °' },
  { value: '100 °', label: '100 °' },
  { value: '110 °', label: '110 °' },
  { value: '120 °', label: '120 °' },
  { value: '130 °', label: '130 °' },
  { value: '140 °', label: '140 °' },
  { value: '150 °', label: '150 °' },
  { value: '160 °', label: '160 °' },
  { value: '170 °', label: '170 °' },
  { value: '180 °', label: '180 °' }
]

export const SHOULDER_PROM_80_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '10 °', label: '10 °' },
  { value: '20 °', label: '20 °' },
  { value: '30 °', label: '30 °' },
  { value: '40 °', label: '40 °' },
  { value: '50 °', label: '50 °' },
  { value: '60 °', label: '60 °' },
  { value: '70 °', label: '70 °' },
  { value: '80 °', label: '80 °' }
]
export const SHOULDER_PROM_90_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '0 °', label: '0 °' },
  { value: '10 °', label: '10 °' },
  { value: '20 °', label: '20 °' },
  { value: '30 °', label: '30 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' },
  { value: '55 °', label: '55 °' },
  { value: '60 °', label: '60 °' },
  { value: '65 °', label: '65 °' },
  { value: '70 °', label: '70 °' },
  { value: '75 °', label: '75 °' },
  { value: '80 °', label: '80 °' },
  { value: '85 °', label: '85 °' },
  { value: '90 °', label: '90 °' }
]
export const SHOULDER_PROM_120_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '0 °', label: '0 °' },
  { value: '10 °', label: '10 °' },
  { value: '20 °', label: '20 °' },
  { value: '30 °', label: '30 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' },
  { value: '55 °', label: '55 °' },
  { value: '60 °', label: '60 °' },
  { value: '65 °', label: '65 °' },
  { value: '70 °', label: '70 °' },
  { value: '75 °', label: '75 °' },
  { value: '80 °', label: '80 °' },
  { value: '85 °', label: '85 °' },
  { value: '90 °', label: '90 °' },
  { value: '95 °', label: '95 °' },
  { value: '100 °', label: '100 °' },
  { value: '105 °', label: '105 °' },
  { value: '110 °', label: '110 °' },
  { value: '115 °', label: '115 °' },
  { value: '120 °', label: '120 °' }
]
export const ENDFEEL_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'Normal Soft Tissue', label: 'Normal Soft Tissue' },
  { value: 'Normal Muscular', label: 'Normal Muscular' },
  { value: 'Normal Ligamentous', label: 'Normal Ligamentous' },
  { value: 'Capsular', label: 'Capsular' },
  { value: 'Adhesions/Scarring', label: 'Adhesions/Scarring' },
  { value: 'Bony Block', label: 'Bony Block' },
  { value: 'Bony Grate', label: 'Bony Grate' },
  { value: 'Springy Rebound', label: 'Springy Rebound' },
  { value: 'Pannus', label: 'Pannus' },
  { value: 'Loose', label: 'Loose' },
  { value: 'Empty', label: 'Empty' },
  { value: 'Painful', label: 'Painful' },
  { value: 'Muscle Guarding', label: 'Muscle Guarding' },
  { value: 'Custom', label: 'Custom' }
]

export const ELBOW_PROM_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '(30) °', label: '(30) °' },
  { value: '(25) °', label: '(25) °' },
  { value: '(20) °', label: '(20) °' },
  { value: '(15) °', label: '(15) °' },
  { value: '(10) °', label: '(10) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '0 °', label: '0 °' },
  { value: '1 ° Hyperextension', label: '1 ° Hyperextension' },
  { value: '2 ° Hyperextension', label: '2 ° Hyperextension' },
  { value: '3 ° Hyperextension', label: '3 ° Hyperextension' },
  { value: '4 ° Hyperextension', label: '4 ° Hyperextension' },
  { value: '5 ° Hyperextension', label: '5 ° Hyperextension' },
  { value: '6 ° Hyperextension', label: '6 ° Hyperextension' },
  { value: '7 ° Hyperextension', label: '7 ° Hyperextension' },
  { value: '8 ° Hyperextension', label: '8 ° Hyperextension' },
  { value: '9 ° Hyperextension', label: '9 ° Hyperextension' },
  { value: '10 ° Hyperextension', label: '10 ° Hyperextension' },
  { value: '11 ° Hyperextension', label: '11 ° Hyperextension' },
  { value: '12 ° Hyperextension', label: '12 ° Hyperextension' },
  { value: '13 ° Hyperextension', label: '13 ° Hyperextension' },
  { value: '14 ° Hyperextension', label: '14 ° Hyperextension' },
  { value: '15 ° Hyperextension', label: '15 ° Hyperextension' }
]
export const ELBOW_PROM_150_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '0 °', label: '0 °' },
  { value: '10 °', label: '10 °' },
  { value: '20 °', label: '20 °' },
  { value: '30 °', label: '30 °' },
  { value: '40 °', label: '40 °' },
  { value: '50 °', label: '50 °' },
  { value: '60 °', label: '60 °' },
  { value: '80 °', label: '80 °' },
  { value: '90 °', label: '90 °' },
  { value: '95 °', label: '95 °' },
  { value: '100 °', label: '100 °' },
  { value: '105 °', label: '105 °' },
  { value: '110 °', label: '110 °' },
  { value: '115 °', label: '115 °' },
  { value: '120 °', label: '120 °' },
  { value: '125 °', label: '125 °' },
  { value: '130 °', label: '130 °' },
  { value: '135 °', label: '135 °' },
  { value: '140 °', label: '140 °' },
  { value: '145 °', label: '145 °' },
  { value: '150 °', label: '150 °' }
]
export const ELBOW_PROM_90_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' },
  { value: '55 °', label: '55 °' },
  { value: '60 °', label: '60 °' },
  { value: '65 °', label: '65 °' },
  { value: '70 °', label: '70 °' },
  { value: '75 °', label: '75 °' },
  { value: '80 °', label: '80 °' },
  { value: '85 °', label: '85 °' },
  { value: '90 °', label: '90 °' }
]

export const WRIST_PROM_90_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0 °', label: '0 °' },
  { value: '10 °', label: '10 °' },
  { value: '20 °', label: '20 °' },
  { value: '30 °', label: '30 °' },
  { value: '40 °', label: '40 °' },
  { value: '50 °', label: '50 °' },
  { value: '55 °', label: '55 °' },
  { value: '60 °', label: '60 °' },
  { value: '65 °', label: '65 °' },
  { value: '70 °', label: '70 °' },
  { value: '75 °', label: '75 °' },
  { value: '80 °', label: '80 °' },
  { value: '85 °', label: '85 °' },
  { value: '90 °', label: '90 °' }
]

export const WRIST_PROM_100_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0 °', label: '0 °' },
  { value: '10 °', label: '10 °' },
  { value: '20 °', label: '20 °' },
  { value: '30 °', label: '30 °' },
  { value: '40 °', label: '40 °' },
  { value: '50 °', label: '50 °' },
  { value: '60 °', label: '60 °' },
  { value: '70 °', label: '70 °' },
  { value: '75 °', label: '75 °' },
  { value: '80 °', label: '80 °' },
  { value: '85 °', label: '85 °' },
  { value: '90 °', label: '90 °' },
  { value: '95 °', label: '95 °' },
  { value: '100 °', label: '100 °' }
]

export const WRIST_PROM_60_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' },
  { value: '55 °', label: '55 °' },
  { value: '60 °', label: '60 °' }
]

export const TOE_PROM_75_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '(30) °', label: '(30) °' },
  { value: '(25) °', label: '(25) °' },
  { value: '(20) °', label: '(20) °' },
  { value: '(15) °', label: '(15) °' },
  { value: '(10) °', label: '(10) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' },
  { value: '55 °', label: '55 °' },
  { value: '60 °', label: '60 °' },
  { value: '65 °', label: '65 °' },
  { value: '70 °', label: '70 °' },
  { value: '75 °', label: '75 °' }
]
export const TOE_PROM_40_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '(30) °', label: '(30) °' },
  { value: '(25) °', label: '(25) °' },
  { value: '(20) °', label: '(20) °' },
  { value: '(15) °', label: '(15) °' },
  { value: '(10) °', label: '(10) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' }
]

export const HIP_PROM_OPTION: RomOption[] = [

  { value: 'not_tested', label: 'Not Tested' },
  { value: 'WNL', label: 'WNL' },
  { value: 'WFL', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '130 °', label: '130 °' },
  { value: '125 °', label: '125 °' },
  { value: '120 °', label: '120 °' },
  { value: '115 °', label: '115 °' },
  { value: '110 °', label: '110 °' },
  { value: '105 °', label: '105 °' },
  { value: '100 °', label: '100 °' },
  { value: '95 °', label: '95 °' },
  { value: '90 °', label: '90 °' },
  { value: '85 °', label: '85 °' },
  { value: '80 °', label: '80 °' },
  { value: '60 °', label: '60 °' },
  { value: '40 °', label: '40 °' },
  { value: '20 °', label: '20 °' },
  { value: '0 °', label: '0 °' }
]

export const HIP_PROM_30_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '(30) °', label: '(30) °' },
  { value: '(25) °', label: '(25) °' },
  { value: '(20) °', label: '(20) °' },
  { value: '(15) °', label: '(15) °' },
  { value: '(10) °', label: '(10) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' }
]

export const HIP_PROM_90_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' },
  { value: '55 °', label: '55 °' },
  { value: '60 °', label: '60 °' },
  { value: '65 °', label: '65 °' },
  { value: '70 °', label: '70 °' },
  { value: '80 °', label: '80 °' },
  { value: '85 °', label: '85 °' },
  { value: '90 °', label: '90 °' }
]

export const AnklePROM_50_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '(30) °', label: '(30) °' },
  { value: '(25) °', label: '(25) °' },
  { value: '(20) °', label: '(20) °' },
  { value: '(15) °', label: '(15) °' },
  { value: '(10) °', label: '(10) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' }
]

export const AnklePROM_70_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'Custom', label: 'Custom' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' },
  { value: '55 °', label: '55 °' },
  { value: '60 °', label: '60 °' },
  { value: '65 °', label: '65 °' },
  { value: '70 °', label: '70 °' }
]

export const AnklePROM_30_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '(10) °', label: '(10) °' },
  { value: '(8) °', label: '(8) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '(3) °', label: '(3) °' },
  { value: '0 °', label: '0 °' },
  { value: '2 °', label: '2 °' },
  { value: '4 °', label: '4 °' },
  { value: '6 °', label: '6 °' },
  { value: '8 °', label: '8 °' },
  { value: '10 °', label: '10 °' },
  { value: '12 °', label: '12 °' },
  { value: '14 °', label: '14 °' },
  { value: '16 °', label: '16 °' },
  { value: '18 °', label: '18 °' },
  { value: '20 °', label: '20 °' },
  { value: '22 °', label: '22 °' },
  { value: '24 °', label: '24 °' },
  { value: '26 °', label: '26 °' },
  { value: '28 °', label: '28 °' },
  { value: '30 °', label: '30 °' }
]
export const AnklePROM_20_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '(10) °', label: '(10) °' },
  { value: '(8) °', label: '(8) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '(3) °', label: '(3) °' },
  { value: '0 °', label: '0 °' },
  { value: '2 °', label: '2 °' },
  { value: '4 °', label: '4 °' },
  { value: '6 °', label: '6 °' },
  { value: '8 °', label: '8 °' },
  { value: '10 °', label: '10 °' },
  { value: '12 °', label: '12 °' },
  { value: '14 °', label: '14 °' },
  { value: '16 °', label: '16 °' },
  { value: '18 °', label: '18 °' },
  { value: '20 °', label: '20 °' }
]

export const FStMTPPROM_90_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '(30) °', label: '(30) °' },
  { value: '(25) °', label: '(25) °' },
  { value: '(20) °', label: '(20) °' },
  { value: '(15) °', label: '(15) °' },
  { value: '(10) °', label: '(10) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' },
  { value: '55 °', label: '55 °' },
  { value: '60 °', label: '60 °' },
  { value: '65 °', label: '65 °' },
  { value: '70 °', label: '70 °' },
  { value: '75 °', label: '75 °' },
  { value: '80 °', label: '80 °' },
  { value: '85 °', label: '85 °' },
  { value: '90 °', label: '90 °' }
]
export const FStMTPPROM_75_OPTION: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '(30) °', label: '(30) °' },
  { value: '(25) °', label: '(25) °' },
  { value: '(20) °', label: '(20) °' },
  { value: '(15) °', label: '(15) °' },
  { value: '(10) °', label: '(10) °' },
  { value: '(5) °', label: '(5) °' },
  { value: '0 °', label: '0 °' },
  { value: '5 °', label: '5 °' },
  { value: '10 °', label: '10 °' },
  { value: '15 °', label: '15 °' },
  { value: '20 °', label: '20 °' },
  { value: '25 °', label: '25 °' },
  { value: '30 °', label: '30 °' },
  { value: '35 °', label: '35 °' },
  { value: '40 °', label: '40 °' },
  { value: '45 °', label: '45 °' },
  { value: '50 °', label: '50 °' },
  { value: '55 °', label: '55 °' },
  { value: '60 °', label: '60 °' },
  { value: '65 °', label: '65 °' },
  { value: '70 °', label: '70 °' },
  { value: '75 °', label: '75 °' }
]