import { RomOption } from './rom-types';

export const ROM_TEST_OPTIONS: RomOption[] = [
  { value: 'wfl', label: 'WFL' },
  { value: 'limited', label: 'Limited' },
  { value: 'hypermobile', label: 'Hypermobile' }
];

export const CERVICAL_ROM_OPTIONS: RomOption[] = [
  { value: 'wfl', label: 'WFL' },
  { value: 'limited', label: 'Limited' }
];

export const APPLY_TO_ALL_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wfl', label: 'WFL' },
  { value: 'limited', label: 'Limited' }
];

export const FORWARD_BENDING_OPTIONS: RomOption[] = [
  { value: 'wfl', label: 'WFL' },
  { value: 'limited', label: 'Limited' },
  { value: 'painful', label: 'Painful' },
  { value: 'restricted', label: 'Restricted' }
];

export const ENDFEEL_OPTIONS: RomOption[] = [
  { value: 'soft', label: 'Soft' },
  { value: 'firm', label: 'Firm' },
  { value: 'hard', label: 'Hard' },
  { value: 'empty', label: 'Empty' }
];


export const DEFAULT_APPLY_TO_ALL_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' }
]

// Cervical AROM
export const CERVICAL_AROM_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0' },
  { value: '5', label: '5' },
  { value: '10', label: '10' },
  { value: '15', label: '15' },
  { value: '20', label: '20' },
  { value: '25', label: '25' },
  { value: '30', label: '30' },
  { value: '35', label: '35' },
  { value: '40', label: '40' },
  { value: '45', label: '45' },
  { value: '50', label: '50' },
  { value: '55', label: '55' },
  { value: '60', label: '60' },
  { value: '65', label: '65' },
  { value: '70', label: '70' },
  { value: '75', label: '75' },
  { value: '80', label: '80' },
  { value: '85', label: '85' },
  { value: '90', label: '90' },
  { value: '100', label: '100' }
]
export const CERVICAL_AROM_SPECIAL_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0' },
  { value: '5', label: '5' },
  { value: '10', label: '10' },
  { value: '15', label: '15' },
  { value: '20', label: '20' },
  { value: '25', label: '25' },
  { value: '30', label: '30' },
  { value: '35', label: '35' },
  { value: '40', label: '40' },
  { value: '45', label: '45' },
  { value: '50', label: '50' },
  { value: '55', label: '55' },
  { value: '60', label: '60' },
  { value: '65', label: '65' },
  { value: '70', label: '70' },
  { value: '75', label: '75' },
  { value: '80', label: '80' },
  { value: '85', label: '85' },
  { value: '90', label: '90' },
  { value: '100', label: '100' },
  { value: 'b98', label: '3 Fingers From Chest' },
  { value: 'b99', label: '2 Fingers From Chest' },
  { value: 'b100', label: '1 Finger From Chest' },
  { value: 'b101', label: 'Chin To Chest' }
]

export const COSTOVERTEBRAL_EXPANSION_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '1.0', label: '1.0' },
  { value: '2.0', label: '2.0' },
  { value: '3.0', label: '3.0' },
  { value: '4.0', label: '4.0' },
  { value: '5.0', label: '5.0' },
  { value: '6.0', label: '6.0' },
  { value: '7.0', label: '7.0' },
  { value: '8.0', label: '8.0' },
  { value: '9.0', label: '9.0' },
  { value: '10.0', label: '10.0' }
]

export const LUMBAR_AROM_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0' },
  { value: '5', label: '5' },
  { value: '10', label: '10' },
  { value: '15', label: '15' },
  { value: '20', label: '20' },
  { value: '25', label: '25' },
  { value: '30', label: '30' },
  { value: '35', label: '35' },
  { value: '40', label: '40' },
  { value: '45', label: '45' },
  { value: '50', label: '50' },
  { value: '75', label: '75' },
  { value: '100', label: '100' }
]
export const LUMBAR_AROM_SPECIAL_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0' },
  { value: '5', label: '5' },
  { value: '10', label: '10' },
  { value: '15', label: '15' },
  { value: '20', label: '20' },
  { value: '25', label: '25' },
  { value: '30', label: '30' },
  { value: '35', label: '35' },
  { value: '40', label: '40' },
  { value: '45', label: '45' },
  { value: '50', label: '50' },
  { value: '75', label: '75' },
  { value: '100', label: '100' },
  { value: 'b98', label: '3 Fingers From Chest' },
  { value: 'b99', label: '2 Fingers From Chest' },
  { value: 'b100', label: '1 Finger From Chest' },
  { value: 'b101', label: 'Chin To Chest' }
]

export const THORACIC_AROM_SITTING_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0' },
  { value: '5', label: '5' },
  { value: '10', label: '10' },
  { value: '15', label: '15' },
  { value: '20', label: '20' },
  { value: '25', label: '25' },
  { value: '30', label: '30' },
  { value: '35', label: '35' },
  { value: '40', label: '40' },
  { value: '45', label: '45' },
  { value: '50', label: '50' },
  { value: '75', label: '75' },
  { value: '100', label: '100' }
]
export const THORACIC_AROM_STANDING_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0' },
  { value: '5', label: '5' },
  { value: '10', label: '10' },
  { value: '15', label: '15' },
  { value: '20', label: '20' },
  { value: '25', label: '25' },
  { value: '30', label: '30' },
  { value: '35', label: '35' },
  { value: '40', label: '40' },
  { value: '45', label: '45' },
  { value: '50', label: '50' },
  { value: '75', label: '75' },
  { value: '100', label: '100' }
]
export const SHOULDER_AROM_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '90', label: '90 °' },
  { value: '100', label: '100 °' },
  { value: '110', label: '110 °' },
  { value: '120', label: '120 °' },
  { value: '130', label: '130 °' },
  { value: '140', label: '140 °' },
  { value: '150', label: '150 °' },
  { value: '160', label: '160 °' },
  { value: '170', label: '170 °' },
  { value: '180', label: '180 °' }
]
export const SHOULDER_AROM_Extension_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '20', label: '20 °' },
  { value: '20', label: '20 °' },
  { value: '30', label: '30 °' },
  { value: '40', label: '40 °' },
  { value: '50', label: '50 °' },
  { value: '60', label: '60 °' },
  { value: '70', label: '70 °' },
  { value: '80', label: '80 °' }
]
export const SHOULDER_AROM_External_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'to_opp_side', label: '= to opp side' },
  { value: 'xheek', label: 'Cheek' },
  { value: 'custom', label: 'Custom' },
  { value: 'ear', label: 'Ear' },
  { value: 'subcranial', label: 'Subcranial' },
  { value: 'C3', label: 'C3' },
  { value: 'C4', label: 'C4' },
  { value: 'C5', label: 'C5' },
  { value: 'C6', label: 'C6' },
  { value: 'C7', label: 'C7' },
  { value: 'T1', label: 'T1' },
  { value: 'T2', label: 'T2' },
  { value: 'T3', label: 'T3' },
  { value: 'T4', label: 'T4' },
  { value: 'T5', label: 'T5' }
]
export const SHOULDER_AROM_INTERNAL_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'to_opp_side', label: '= to opp side' },
  { value: 'iliac_crest', label: 'Iliac Crest' },
  { value: 'custom', label: 'Custom' },
  { value: 'gluteals', label: 'Gluteals' },
  { value: 'PSIS', label: 'PSIS' },
  { value: 'sacrum', label: 'Sacrum' },
  { value: 'L5', label: 'L5' },
  { value: 'L4', label: 'L4' },
  { value: 'L3', label: 'L3' },
  { value: 'L2', label: 'L2' },
  { value: 'L1', label: 'L1' },
  { value: 'T12', label: 'T12' },
  { value: 'T11', label: 'T11' },
  { value: 'T10', label: 'T10' },
  { value: 'T9', label: 'T9' },
  { value: 'T8', label: 'T8' },
  { value: 'T7', label: 'T7' },
  { value: 'T6', label: 'T6' },
  { value: 'T5_or_greater', label: 'T5 or >' }
]
export const SHOULDER_AROM_POSITION_ABDUCTION_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0 °' },
  { value: '10', label: '10 °' },
  { value: '20', label: '20 °' },
  { value: '30', label: '30 °' },
  { value: '40', label: '40 °' },
  { value: '45', label: '45 °' },
  { value: '50', label: '50 °' },
  { value: '55', label: '55 °' },
  { value: '60', label: '60 °' },
  { value: '65', label: '65 °' },
  { value: '70', label: '70 °' },
  { value: '75', label: '75 °' },
  { value: '80', label: '80 °' },
  { value: '85', label: '85 °' },
  { value: '90', label: '90 °' },
  { value: '95', label: '95 °' },
  { value: '100', label: '100 °' }
]

export const ALBOW_AROM_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '30', label: '(30) °' },
  { value: '25', label: '(25) °' },
  { value: '20', label: '(20) °' },
  { value: '15', label: '(15) °' },
  { value: '10', label: '(10) °' },
  { value: '5', label: '(5) °' },
  { value: '0', label: '0 °' },
  { value: '1_Hyperextension', label: '1 ° Hyperextension' },
  { value: '2_Hyperextension', label: '2 ° Hyperextension' },
  { value: '3_Hyperextension', label: '3 ° Hyperextension' },
  { value: '4_Hyperextension', label: '4 ° Hyperextension' },
  { value: '5_Hyperextension', label: '5 ° Hyperextension' },
  { value: '6_Hyperextension', label: '6 ° Hyperextension' },
  { value: '7_Hyperextension', label: '7 ° Hyperextension' },
  { value: '8_Hyperextension', label: '8 ° Hyperextension' },
  { value: '9_Hyperextension', label: '9 ° Hyperextension' },
  { value: '10_Hyperextension', label: '10 ° Hyperextension' },
  { value: '11_Hyperextension', label: '11 ° Hyperextension' },
  { value: '12_Hyperextension', label: '12 ° Hyperextension' },
  { value: '13_Hyperextension', label: '13 ° Hyperextension' },
  { value: '14_Hyperextension', label: '14 ° Hyperextension' },
  { value: '15_Hyperextension', label: '15 ° Hyperextension' }
]
export const ALBOW_AROM_FLEXION_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0 °' },
  { value: '10', label: '10 °' },
  { value: '20', label: '20 °' },
  { value: '30', label: '30 °' },
  { value: '40', label: '40 °' },
  { value: '50', label: '50 °' },
  { value: '60', label: '60 °' },
  { value: '80', label: '80 °' },
  { value: '90', label: '90 °' },
  { value: '95', label: '95 °' },
  { value: '100', label: '100 °' },
  { value: '105', label: '105 °' },
  { value: '110', label: '110 °' },
  { value: '115', label: '115 °' },
  { value: '120', label: '120 °' },
  { value: '125', label: '125 °' },
  { value: '130', label: '130 °' },
  { value: '135', label: '135 °' },
  { value: '140', label: '140 °' },
  { value: '145', label: '145 °' },
  { value: '150', label: '150 °' }
]
export const ALBOW_AROM_SUPINATION_PRONATION_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0 °' },
  { value: '5', label: '5 °' },
  { value: '10', label: '10 °' },
  { value: '15', label: '15 °' },
  { value: '20', label: '20 °' },
  { value: '25', label: '25 °' },
  { value: '30', label: '30 °' },
  { value: '35', label: '35 °' },
  { value: '40', label: '40 °' },
  { value: '45', label: '45 °' },
  { value: '50', label: '50 °' },
  { value: '55', label: '55 °' },
  { value: '60', label: '60 °' },
  { value: '65', label: '65 °' },
  { value: '70', label: '70 °' },
  { value: '75', label: '75 °' },
  { value: '80', label: '80 °' },
  { value: '85', label: '85 °' },
  { value: '90', label: '90 °' }
]

export const WRIST_AROM_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '30', label: '(30) °' },
  { value: '25', label: '(25) °' },
  { value: '20', label: '(20) °' },
  { value: '15', label: '(15) °' },
  { value: '10', label: '(10) °' },
  { value: '5', label: '(5) °' },
  { value: '0', label: '0 °' },
  { value: '1_Hyperextension', label: '1 ° Hyperextension' },
  { value: '2_Hyperextension', label: '2 ° Hyperextension' },
  { value: '3_Hyperextension', label: '3 ° Hyperextension' },
  { value: '4_Hyperextension', label: '4 ° Hyperextension' },
  { value: '5_Hyperextension', label: '5 ° Hyperextension' },
  { value: '6_Hyperextension', label: '6 ° Hyperextension' },
  { value: '7_Hyperextension', label: '7 ° Hyperextension' },
  { value: '8_Hyperextension', label: '8 ° Hyperextension' },
  { value: '9_Hyperextension', label: '9 ° Hyperextension' },
  { value: '10_Hyperextension', label: '10 ° Hyperextension' },
  { value: '11_Hyperextension', label: '11 ° Hyperextension' },
  { value: '12_Hyperextension', label: '12 ° Hyperextension' },
  { value: '13_Hyperextension', label: '13 ° Hyperextension' },
  { value: '14_Hyperextension', label: '14 ° Hyperextension' },
  { value: '15_Hyperextension', label: '15 ° Hyperextension' }
]
export const WRIST_AROM_FLEXION_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0 °' },
  { value: '10', label: '10 °' },
  { value: '20', label: '20 °' },
  { value: '30', label: '30 °' },
  { value: '40', label: '40 °' },
  { value: '50', label: '50 °' },
  { value: '60', label: '60 °' },
  { value: '80', label: '80 °' },
  { value: '90', label: '90 °' },
  { value: '95', label: '95 °' },
  { value: '100', label: '100 °' },
  { value: '105', label: '105 °' },
  { value: '110', label: '110 °' },
  { value: '115', label: '115 °' },
  { value: '120', label: '120 °' },
  { value: '125', label: '125 °' },
  { value: '130', label: '130 °' },
  { value: '135', label: '135 °' },
  { value: '140', label: '140 °' },
  { value: '145', label: '145 °' },
  { value: '150', label: '150 °' }
]
export const WRIST_AROM_SUPINATION_PRONATION_OPTIONS: RomOption[] = [
  { value: 'not_tested', label: 'Not Tested' },
  { value: 'wnl', label: 'WNL' },
  { value: 'wfl', label: 'WFL' },
  { value: 'custom', label: 'Custom' },
  { value: '0', label: '0 °' },
  { value: '5', label: '5 °' },
  { value: '10', label: '10 °' },
  { value: '15', label: '15 °' },
  { value: '20', label: '20 °' },
  { value: '25', label: '25 °' },
  { value: '30', label: '30 °' },
  { value: '35', label: '35 °' },
  { value: '40', label: '40 °' },
  { value: '45', label: '45 °' },
  { value: '50', label: '50 °' },
  { value: '55', label: '55 °' },
  { value: '60', label: '60 °' },
  { value: '65', label: '65 °' },
  { value: '70', label: '70 °' },
  { value: '75', label: '75 °' },
  { value: '80', label: '80 °' },
  { value: '85', label: '85 °' },
  { value: '90', label: '90 °' }
]

