import { ThoracicAROMStanding } from "../config/thoracic-arom-standing-config";
import { FstIPAROM } from "./1stIPAROM";
import { FsttMTPAROM } from "./1stMTPAROM";
import { AdditionalComments } from "./AdditionalComments";
import { AnkleAROMM } from "./AnkleAROMM";
import { AnklePROMM } from "./AnklePROMM";
import { CervicalAROM } from "./CervicalAROM";
import { ElbowAROM } from "./ElbowAROM";
import { ElbowPROM } from "./ElbowPROM";
import { HandAROMPROM } from "./HandAROM-PROM";
import { HipAROMM } from "./HipAROMM";
import { HipPROMM } from "./HipPROMM";
import { KneeAROMM } from "./KneeAROM";
import { KneePROMM } from "./KneePROM";
import { LumbarAROM } from "./LumbarAROM";
import { NoLimitationsNoted } from "./NoLimitationsNoted";
import { ShoulderAROM } from "./ShoulderAROM";
import { ShoulderPROM } from "./ShoulderPROM";
import { ThoracicAROMSittingwithPassiveOverpressure } from "./ThoracicAROMSittingwithPassiveOverpressure";
import { ThoracicAROMStandingM } from "./ThoracicAROMStandingM";
import { ToeAROMM } from "./ToeAROMM";
import { ToePROMM } from "./ToePROMM";
import { WristAROMM } from "./WristAROMM";
import { WristPROM } from "./WristPROMM";

export interface RangeOfMotion {
  costovertebralExpansion: boolean;
  noLimitationsNoted: NoLimitationsNoted;
  cervicalAROM: CervicalAROM;
  shoulderAROM: ShoulderAROM;
  shoulderPROM: ShoulderPROM;
  elbowAROM: ElbowAROM;
  elbowPROM: ElbowPROM;
  wristAROM: WristAROMM;
  wristPROM: WristPROM;
  handAROMPROM: HandAROMPROM;
  thoracicAROMSittingwithPassiveOverpressure: ThoracicAROMSittingwithPassiveOverpressure;
  thoracicAROMStanding: ThoracicAROMStandingM;
  lumbarAROM: LumbarAROM;
  hipAROM: HipAROMM;
  hipPROM: HipPROMM;
  kneeAROM: KneeAROMM;
  kneePROM: KneePROMM;
  ankleAROM: AnkleAROMM;
  anklePROM: AnklePROMM;
  fstMTPAROM: FsttMTPAROM;
  fstMTPPROM: FsttMTPAROM;
  fstIPAROM: FstIPAROM;
  fstIPPROM: FstIPAROM;
  toeAROM: ToeAROMM;
  toePROM: ToePROMM;
  additionalComments: AdditionalComments;
}
