import { Injectable } from '@angular/core';
import { NeuroVascular } from '../models/NeuroVascular';

@Injectable({
  providedIn: 'root'
})
export class NeuroVascularMapperService {

  constructor() { }

  private readonly formToDto: Record<string, string> = {
    'complaints_of_any_radicular_symptoms_in_either_extremity': 'complaintsOfAnyRadicularSymptomsInEitherExtremity',
    'cranial_nerve_screen': 'cranialNerveScreen',
    'myotomes_upper': 'myotomesUpper',
    'myotomes_lower': 'myotomesLower',
    'dermatomes_upper': 'dermatomesUpper',
    'dermatomes_lower': 'dermatomesLower',
    'upper_reflexes': 'upperReflexes',
    'lower_reflexes': 'lowerReflexes',
    'neural_tissue_tension_upper': 'neuralTissueTensionUpper',
    'neural_tissue_tension_lower': 'neuralTissueTensionLower',
    'vascular': 'vascular',
    'vertebral_artery': 'vertebralArtery',
    'allen_s_test_circulation': 'allenSTestCirculation',
    'capillary_refill': 'capillaryRefill',
    'homan_s_sign': 'homanSSign',
    'thoracic_outlet': 'thoracicOutlet',
    'lasegue_s_slr': 'lasegueSSlr',
    'slump': 'slump',
    'quadrant_testing': 'quadrantTesting',
    'prone_knee_bend_nachlas': 'proneKneeBendNachlas',
    'kernig_brudzinski_test': 'kernigBrudzinskiTest',
    'cram_test': 'cramTest',
    'seated_dural_stretch': 'seatedDuralStretch',
    'semmes_weinstein_lower': 'semmesWeinsteinLower',
    'fst_toe_semmes_weinstein_lower': 'fstToeSemmesWeinsteinLower',
    'snd_toe_semmes_weinstein_lower': 'sndToeSemmesWeinsteinLower',
    'thrd_toe_semmes_weinstein_lower': 'thrdToeSemmesWeinsteinLower',
    'frth_toe_semmes_weinstein_lower': 'frthToeSemmesWeinsteinLower',
    'fifth_toe_semmes_weinstein_lower': 'fifthToeSemmesWeinsteinLower',
    'plantar_surface_semmes_weinstein_lower': 'plantarSurfaceSemmesWeinsteinLower',
    'dorsal_surface_semmes_weinstein_lower': 'dorsalSurfaceSemmesWeinsteinLower',
    'semmes_weinstein_upper': 'semmesWeinsteinUpper',
    'thumb_semmes_weinstein_upper': 'thumbSemmesWeinsteinUpper',
    'index_finger_semmes_weinstein_upper': 'indexFingerSemmesWeinsteinUpper',
    'middle_finger_semmes_weinstein_upper': 'middleFingerSemmesWeinsteinUpper',
    'ring_finger_semmes_weinstein_upper': 'ringFingerSemmesWeinsteinUpper',
    'small_finger_semmes_weinstein_upper': 'smallFingerSemmesWeinsteinUpper',
    'tinel_s_lower': 'tinelSLower',
    'tinel_s_upper': 'tinelSUpper',
    'transverse_ligament_stability': 'transverseLigamentStability',
    'additional_comments': 'additionalComments',
    'additional_comments_text': 'additionalCommentsText',
    'cranial_nerve_screen_unilateral_smell_(cn_1)': 'cranialNerveScreenUnilateralSmell_cn_1',
    'cranial_nerve_screen_negative_(normal)': 'cranialNerveScreenNegative_normal',
    'cranial_nerve_screen_confrontation_(cn_2)': 'cranialNerveScreenConfrontation_cn_2',
    'cranial_nerve_screen_not_tested': 'cranialNerveScreenNotTested',
    'cranial_nerve_screen_hall-pike_(cn_8_coch)': 'cranialNerveScreenHall_pike_cn_8Coch',
    'cranial_nerve_screen_finger_rustle_(cn_8_coch)': 'cranialNerveScreenFingerRustle_cn_8Coch',
    'cranial_nerve_screen_bone_conduction_(cn_8_coch)': 'cranialNerveScreenBoneConduction_cn_8Coch',
    'cranial_nerve_screen_convergence_(cn_3,4,6)': 'cranialNerveScreenConvergence_cn_3_4_6',
    'cranial_nerve_screen_facial_sensation_(cn_5)': 'cranialNerveScreenFacialSensation_cn_5',
    'cranial_nerve_screen_jaw_jerk_/_clonus_(cn_5)': 'cranialNerveScreenJawJerk_Clonus_cn_5',
    'cranial_nerve_screen_smile_(cn_7)': 'cranialNerveScreenSmile_cn_7',
    'cranial_nerve_screen_frown_(cn_7)': 'cranialNerveScreenFrown_cn_7',
    'cranial_nerve_screen_body_tilt_(cn_8_vest)': 'cranialNerveScreenBodyTilt_cn_8Vest',
    'cranial_nerve_screen_swallowing_(cn_9)': 'cranialNerveScreenSwallowing_cn_9',
    'cranial_nerve_screen_uvula_test_(cn_10)': 'cranialNerveScreenUvulaTest_cn_10',
    'cranial_nerve_screen_trapezius_/_scm_(cn_11)': 'cranialNerveScreenTrapezius_Scm_cn_11',
    'cranial_nerve_screen_tongue_protrusion_(cn_12)': 'cranialNerveScreenTongueProtrusion_cn_12',
    'myotomes_upper_chin_in': 'myotomesUpperChinIn',
    'myotomes_upper_chin_in_custom': 'myotomesUpperChinInCustom',
    'myotomes_upper_chin_up': 'myotomesUpperChinUp',
    'myotomes_upper_chin_up_custom': 'myotomesUpperChinUpCustom',
    'myotomes_upper_c3_lat_cerv_flexion_right': 'myotomesUpperC3LatCervFlexionRight',
    'myotomes_upper_c3_lat_cerv_flexion_right_custom': 'myotomesUpperC3LatCervFlexionRightCustom',
    'myotomes_upper_c3_lat_cerv_flexion_left': 'myotomesUpperC3LatCervFlexionLeft',
    'myotomes_upper_c3_lat_cerv_flexion_left_custom': 'myotomesUpperC3LatCervFlexionLeftCustom',
    'myotomes_upper_c4_shoulder_elevation_right': 'myotomesUpperC4ShoulderElevationRight',
    'myotomes_upper_c4_shoulder_elevation_right_custom': 'myotomesUpperC4ShoulderElevationRightCustom',
    'myotomes_upper_c4_shoulder_elevation_left': 'myotomesUpperC4ShoulderElevationLeft',
    'myotomes_upper_c4_shoulder_elevation_left_custom': 'myotomesUpperC4ShoulderElevationLeftCustom',
    'myotomes_upper_c5_shoulder_abduction_right': 'myotomesUpperC5ShoulderAbductionRight',
    'myotomes_upper_c5_shoulder_abduction_right_custom': 'myotomesUpperC5ShoulderAbductionRightCustom',
    'myotomes_upper_c5_shoulder_abduction_left': 'myotomesUpperC5ShoulderAbductionLeft',
    'myotomes_upper_c5_shoulder_abduction_left_custom': 'myotomesUpperC5ShoulderAbductionLeftCustom',
    'myotomes_upper_c6_wrist_extension_right': 'myotomesUpperC6WristExtensionRight',
    'myotomes_upper_c6_wrist_extension_right_custom': 'myotomesUpperC6WristExtensionRightCustom',
    'myotomes_upper_c6_wrist_extension_left': 'myotomesUpperC6WristExtensionLeft',
    'myotomes_upper_c6_wrist_extension_left_custom': 'myotomesUpperC6WristExtensionLeftCustom',
    'myotomes_upper_c7_triceps_right': 'myotomesUpperC7TricepsRight',
    'myotomes_upper_c7_triceps_right_custom': 'myotomesUpperC7TricepsRightCustom',
    'myotomes_upper_c7_triceps_left': 'myotomesUpperC7TricepsLeft',
    'myotomes_upper_c7_triceps_left_custom': 'myotomesUpperC7TricepsLeftCustom',
    'myotomes_upper_c8_1st_extension_right': 'myotomesUpperC8_1stExtensionRight',
    'myotomes_upper_c8_1st_extension_right_custom': 'myotomesUpperC8_1stExtensionRightCustom',
    'myotomes_upper_c8_1st_extension_left': 'myotomesUpperC8_1stExtensionLeft',
    'myotomes_upper_c8_1st_extension_left_custom': 'myotomesUpperC8_1stExtensionLeftCustom',
    'myotomes_upper_t1_hand_intrinsics_right': 'myotomesUpperT1HandIntrinsicsRight',
    'myotomes_upper_t1_hand_intrinsics_right_custom': 'myotomesUpperT1HandIntrinsicsRightCustom',
    'myotomes_upper_t1_hand_intrinsics_left': 'myotomesUpperT1HandIntrinsicsLeft',
    'myotomes_upper_t1_hand_intrinsics_left_custom': 'myotomesUpperT1HandIntrinsicsLeftCustom',
    'myotomes_upper_comments': 'myotomesUpperComments',
    'my_otomes_lower_apply_to_all': 'myOtomesLowerApplyToAll',
    'my_otomes_lower_l1,_2_iliopsoas_right': 'myOtomesLowerL12IliopsoasRight',
    'my_otomes_lower_l1,_2_iliopsoas_left': 'myOtomesLowerL12IliopsoasLeft',
    'my_otomes_lower_l3_quadriceps_right': 'myOtomesLowerL3QuadricepsRight',
    'my_otomes_lower_l3_quadriceps_left': 'myOtomesLowerL3QuadricepsLeft',
    'my_otomes_lower_l4_anterior_tibialis_right': 'myOtomesLowerL4AnteriorTibialisRight',
    'my_otomes_lower_l4_anterior_tibialis_left': 'myOtomesLowerL4AnteriorTibialisLeft',
    'my_otomes_lower_l5_ehl_right': 'myOtomesLowerL5EhlRight',
    'my_otomes_lower_l5_ehl_left': 'myOtomesLowerL5EhlLeft',
    'my_otomes_lower_s1_gastroc_right': 'myOtomesLowerS1GastrocRight',
    'my_otomes_lower_s1_gastroc_left': 'myOtomesLowerS1GastrocLeft',
    'my_otomes_lower_s2_hamstrings_right': 'myOtomesLowerS2HamstringsRight',
    'my_otomes_lower_s2_hamstrings_left': 'myOtomesLowerS2HamstringsLeft',
    'my_otomes_lower__comments': 'myOtomesLower_Comments',
    'dermatomes_upper_apply_to_all': 'dermatomesUpperApplyToAll',
    'dermatomes_upper_c4_right': 'dermatomesUpperC4Right',
    'dermatomes_upper_c4_left': 'dermatomesUpperC4Left',
    'dermatomes_upper_c5_right': 'dermatomesUpperC5Right',
    'dermatomes_upper_c5_left': 'dermatomesUpperC5Left',
    'dermatomes_upper_c6_right': 'dermatomesUpperC6Right',
    'dermatomes_upper_c6_left': 'dermatomesUpperC6Left',
    'dermatomes_upper_c7_right': 'dermatomesUpperC7Right',
    'dermatomes_upper_c7_left': 'dermatomesUpperC7Left',
    'dermatomes_upper_c8_right': 'dermatomesUpperC8Right',
    'dermatomes_upper_c8_left': 'dermatomesUpperC8Left',
    'dermatomes_upper_t1_right': 'dermatomesUpperT1Right',
    'dermatomes_upper_t1_left': 'dermatomesUpperT1Left',
    'dermatomes_upper_comments': 'dermatomesUpperComments',
    'dermatomes_lower_l1,_2_mid_anterior_thigh_right': 'dermatomesLowerL1_2MidAnteriorThighRight',
    'dermatomes_lower_l1,_2_mid_anterior_thigh_left': 'dermatomesLowerL1_2MidAnteriorThighLeft',
    'dermatomes_lower_l3_distal_inner_thigh_right': 'dermatomesLowerL3DistalInnerThighRight',
    'dermatomes_lower_l3_distal_inner_thigh_left': 'dermatomesLowerL3DistalInnerThighLeft',
    'dermatomes_lower_l4_anterior_tibialis_right': 'dermatomesLowerL4AnteriorTibialisRight',
    'dermatomes_lower_l4_anterior_tibialis_left': 'dermatomesLowerL4AnteriorTibialisLeft',
    'dermatomes_lower_l5_ehl_right': 'dermatomesLowerL5EhlRight',
    'dermatomes_lower_l5_ehl_left': 'dermatomesLowerL5EhlLeft',
    'dermatomes_lower_s1_lateral_foot_right': 'dermatomesLowerS1LateralFootRight',
    'dermatomes_lower_s1_lateral_foot_left': 'dermatomesLowerS1LateralFootLeft',
    'dermatomes_lower_s2_mid_gastoc/hamstring_right': 'dermatomesLowerS2MidGastochamstringRight',
    'dermatomes_lower_s2_mid_gastoc/hamstring_left': 'dermatomesLowerS2MidGastochamstringLeft',
    'dermatomes_lower___comments': 'dermatomesLower__Comments',
    'upper_reflexes_biceps_c5,6_right': 'upperReflexesBicepsC5_6Right',
    'upper_reflexes_biceps_c5,6_left': 'upperReflexesBicepsC5_6Left',
    'upper_reflexes_triceps_c7_right': 'upperReflexesTricepsC7Right',
    'upper_reflexes_triceps_c7_left': 'upperReflexesTricepsC7Left',
    'upper_reflexes_brachial_radialis_c5,6_right': 'upperReflexesBrachialRadialisC56Right',
    'upper_reflexes_brachial_radialis_c5,6_left': 'upperReflexesBrachialRadialisC5_6Left',
    'lower_reflexes_apply_to_all': 'lowerReflexesApplyToAll',
    'lower_reflexes_knee_jerk_(l4)_right': 'lowerReflexesKneeJerk_l4_Right',
    'lower_reflexes_knee_jerk_(l4)_left': 'lowerReflexesKneeJerk_l4_Left',
    'lower_reflexes_ankle_jerk_(s1)_right': 'lowerReflexesAnkleJerk_s1_Right',
    'lower_reflexes_ankle_jerk_(s1)_left': 'lowerReflexesAnkleJerk_s1_Left',
    'lower_reflexes_comments': 'lowerReflexesComments',
    'neural_tissue_tension_upper_median_nerve_right': 'neuralTissueTensionUpperMedianNerveRight',
    'neural_tissue_tension_upper_median_nerve_left': 'neuralTissueTensionUpperMedianNerveLeft',
    'neural_tissue_tension_upper_radial_nerve_right': 'neuralTissueTensionUpperRadialNerveRight',
    'neural_tissue_tension_upper_radial_nerve_left': 'neuralTissueTensionUpperRadialNerveLeft',
    'neural_tissue_tension_upper_ulnar_nerve_right': 'neuralTissueTensionUpperUlnarNerveRight',
    'neural_tissue_tension_upper_ulnar_nerve_left': 'neuralTissueTensionUpperUlnarNerveLeft',
    'neural_tissue_tension_upper_musculocutaneous_nerve_right': 'neuralTissueTensionUpperMusculocutaneousNerveRight',
    'neural_tissue_tension_upper_musculocutaneous_nerve_left': 'neuralTissueTensionUpperMusculocutaneousNerveLeft',
    'neural_tissue_tension_upper_axillary_nerve_right': 'neuralTissueTensionUpperAxillaryNerveRight',
    'neural_tissue_tension_upper_axillary_nerve_left': 'neuralTissueTensionUpperAxillaryNerveLeft',
    'neural_tissue_tension_upper_suprascapular_nerve_right': 'neuralTissueTensionUpperSuprascapularNerveRight',
    'neural_tissue_tension_upper_suprascapular_nerve_left': 'neuralTissueTensionUpperSuprascapularNerveLeft',
    'neural_tissue_tension_lower_sciatic_nerve_right': 'neuralTissueTensionLowerSciaticNerveRight',
    'neural_tissue_tension_lower_sciatic_nerve_left': 'neuralTissueTensionLowerSciaticNerveLeft',
    'neural_tissue_tension_lower_common_peroneal_nerve_right': 'neuralTissueTensionLowerCommonPeronealNerveRight',
    'neural_tissue_tension_lower_common_peroneal_nerve_left': 'neuralTissueTensionLowerCommonPeronealNerveLeft',
    'neural_tissue_tension_lower_tibial_nerve_right': 'neuralTissueTensionLowerTibialNerveRight',
    'neural_tissue_tension_lower_tibial_nerve_left': 'neuralTissueTensionLowerTibialNerveLeft',
    'vascular_popliteal_artery_right': 'vascularPoplitealArteryRight',
    'vascular_popliteal_artery_left': 'vascularPoplitealArteryLeft',
    'vascular_pedal_pulse_right': 'vascularPedalPulseRight',
    'vascular_pedal_pulse_left': 'vascularPedalPulseLeft',
    'vascular_posterior_tibial_artery_right': 'vascularPosteriorTibialArteryRight',
    'vascular_posterior_tibial_artery_left': 'vascularPosteriorTibialArteryLeft',
    'allens_test_circulation_radial_artery_right': 'allensTestCirculationRadialArteryRight',
    'allens_test_circulation_radial_artery_left': 'allensTestCirculationRadialArteryLeft',
    'allens_test_circulation_ulnar_artery_right': 'allensTestCirculationUlnarArteryRight',
    'allens_test_circulation_ulnar_artery_left': 'allensTestCirculationUlnarArteryLeft',
    'capillary_refill_capillary_refill_right': 'capillaryRefillCapillaryRefillRight',
    'capillary_refill_capillary_refill_left': 'capillaryRefillCapillaryRefillLeft',
    'homans_sign_homan\'s_sign_right': 'homansSignHomansSignRight',
    'homans_sign_homan\'s_sign_left': 'homansSignHomansSignLeft',
    'thoracic_outlet_adson\'s_test_right': 'thoracicOutletAdsonsTestRight',
    'thoracic_outlet_adson\'s_test_left': 'thoracicOutletAdsonsTestLeft',
    'thoracic_outlet_roos\'_test_right': 'thoracicOutletRoosTestRight',
    'thoracic_outlet_roos\'_test_left': 'thoracicOutletRoosTestLeft',
    'lasegues_slr_apply_to_all': 'laseguesSlrApplyToAll',
    'lasegues_slr_lasegue\'s_slr_right': 'laseguesSlrLaseguesSlrRight',
    'lasegues_slr_lasegue\'s_slr_left': 'laseguesSlrLaseguesSlrLeft',
    'lasegues_slr_comments': 'laseguesSlrComments',
    'slump_slump_right': 'slumpSlumpRight',
    'slump_slump_left': 'slumpSlumpLeft',
    'quadrant_testing_quadrant_testing_right': 'quadrantTestingQuadrantTestingRight',
    'quadrant_testing_quadrant_testing_left': 'quadrantTestingQuadrantTestingLeft',
    'prone_knee_bend_nachlas_apply_to_all': 'proneKneeBendNachlasApplyToAll',
    'prone_knee_bend_nachlas_prone_knee_bend_(nachlas)_right': 'proneKneeBendNachlasProneKneeBend_nachlas_Right',
    'prone_knee_bend_nachlas_prone_knee_bend_(nachlas)_left': 'proneKneeBendNachlasProneKneeBend_nachlas_Left',
    'prone_knee_bend_nachlas_comments': 'proneKneeBendNachlasComments',
    'kernig_brudzinski_test_kernig/brudzinski_test_right': 'kernigBrudzinskiTestKernigbrudzinskiTestRight',
    'kernig_brudzinski_test_kernig/brudzinski_test_left': 'kernigBrudzinskiTestKernigbrudzinskiTestLeft',
    'cram_test_cram_test_right': 'cramTestCramTestRight',
    'cram_test_cram_test_left': 'cramTestCramTestLeft',
    'seated_dural_stretch_seated_dural_stretch_right': 'seatedDuralStretchSeatedDuralStretchRight',
    'seated_dural_stretch_seated_dural_stretch_left': 'seatedDuralStretchSeatedDuralStretchLeft',
    'seated_dural_stretch_comments': 'seatedDuralStretchComments',
    'first_toet_right': 'firstToetRight',
    'first_toet_right_text': 'firstToetRightText',
    'first_toet_left': 'firstToetLeft',
    'first_toet_left_text': 'firstToetLeftText',
    'second_toe_right': 'secondToeRight',
    'second_toe_right_text': 'secondToeRightText',
    'second_toe_left': 'secondToeLeft',
    'second_toe_left_text': 'secondToeLeftText',
    'third_toe_right': 'thirdToeRight',
    'third_toe_right_text': 'thirdToeRightText',
    'third_toe_left': 'thirdToeLeft',
    'third_toe_left_text': 'thirdToeLeftText',
    'fourth_toe_right': 'fourthToeRight',
    'fourth_toe_right_text': 'fourthToeRightText',
    'fourth_toe_left': 'fourthToeLeft',
    'fourth_toe_left_text': 'fourthToeLeftText',
    'fifth_toe_right': 'fifthToeRight',
    'fifth_toe_right_text': 'fifthToeRightText',
    'fifth_toe_left': 'fifthToeLeft',
    'fifth_toe_left_text': 'fifthToeLeftText',
    'plantar_surface_right': 'plantarSurfaceRight',
    'plantar_surface_right_text': 'plantarSurfaceRightText',
    'plantar_surface_left': 'plantarSurfaceLeft',
    'plantar_surface_left_text': 'plantarSurfaceLeftText',
    'dorsal_surface_right': 'dorsalSurfaceRight',
    'dorsal_surface_right_text': 'dorsalSurfaceRightText',
    'dorsal_surface_left': 'dorsalSurfaceLeft',
    'dorsal_surface_left_text': 'dorsalSurfaceLeftText',
    'thumb_radial_right': 'thumbRadialRight',
    'thumb_radial_right_text': 'thumbRadialRightText',
    'thumb_radial_left': 'thumbRadialLeft',
    'thumb_radial_left_text': 'thumbRadialLeftText',
    'thumb_ulnar_right': 'thumbUlnarRight',
    'thumb_ulnar_right_text': 'thumbUlnarRightText',
    'thumb_ulnar_left': 'thumbUlnarLeft',
    'thumb_ulnar_left_text': 'thumbUlnarLeftText',
    'index_finger_radial_right': 'indexFingerRadialRight',
    'index_finger_radial_right_text': 'indexFingerRadialRightText',
    'index_finger_radial_left': 'indexFingerRadialLeft',
    'index_finger_radial_left_text': 'indexFingerRadialLeftText',
    'index_finger_ulnar_right': 'indexFingerUlnarRight',
    'index_finger_ulnar_right_text': 'indexFingerUlnarRightText',
    'index_finger_ulnar_left': 'indexFingerUlnarLeft',
    'index_finger_ulnar_left_text': 'indexFingerUlnarLeftText',
    'middle_finger_radial_right': 'middleFingerRadialRight',
    'middle_finger_radial_right_text': 'middleFingerRadialRightText',
    'middle_finger_radial_left': 'middleFingerRadialLeft',
    'middle_finger_radial_left_text': 'middleFingerRadialLeftText',
    'middle_finger_ulnar_right': 'middleFingerUlnarRight',
    'middle_finger_ulnar_right_text': 'middleFingerUlnarRightText',
    'middle_finger_ulnar_left': 'middleFingerUlnarLeft',
    'middle_finger_ulnar_left_text': 'middleFingerUlnarLeftText',
    'ring_finger_radial_right': 'ringFingerRadialRight',
    'ring_finger_radial_right_text': 'ringFingerRadialRightText',
    'ring_finger_radial_left': 'ringFingerRadialLeft',
    'ring_finger_radial_left_text': 'ringFingerRadialLeftText',
    'ring_finger_ulnar_right': 'ringFingerUlnarRight',
    'ring_finger_ulnar_right_text': 'ringFingerUlnarRightText',
    'ring_finger_ulnar_left': 'ringFingerUlnarLeft',
    'ring_finger_ulnar_left_text': 'ringFingerUlnarLeftText',
    'small_finger_radial_right': 'smallFingerRadialRight',
    'small_finger_radial_right_text': 'smallFingerRadialRightText',
    'small_finger_radial_left': 'smallFingerRadialLeft',
    'small_finger_radial_left_text': 'smallFingerRadialLeftText',
    'small_finger_ulnar_right': 'smallFingerUlnarRight',
    'small_finger_ulnar_right_text': 'smallFingerUlnarRightText',
    'small_finger_ulnar_left': 'smallFingerUlnarLeft',
    'small_finger_ulnar_left_text': 'smallFingerUlnarLeftText',
    'tinels_lower_tarsal_tunnel_-_posterior_tibial_nerve_right': 'tinelsLowerTarsalTunnel_PosteriorTibialNerveRight',
    'tinels_lower_tarsal_tunnel_-_posterior_tibial_nerve_left': 'tinelsLowerTarsalTunnel_PosteriorTibialNerveLeft',
    'tinels_lower_fibular_head_-_common_peroneal_nerve_right': 'tinelsLowerFibularHead_CommonPeronealNerveRight',
    'tinels_lower_fibular_head_-_common_peroneal_nerve_left': 'tinelsLowerFibularHead_CommonPeronealNerveLeft',
    'tinels_upper_volar_carpals-_median_nerve_right': 'tinelsUpperVolarCarpals_MedianNerveRight',
    'tinels_upper_volar_carpals-_median_nerve_left': 'tinelsUpperVolarCarpals_MedianNerveLeft',
    'tinels_upper_cubital_tunnel-ulnar_nerve_right': 'tinelsUpperCubitalTunnel_ulnarNerveRight',
    'tinels_upper_cubital_tunnel-ulnar_nerve_left': 'tinelsUpperCubitalTunnel_ulnarNerveLeft',
    'tinels_upper_guyon\'s_canal-_ulnar_nerve_right': 'tinelsUpperGuyonsCanal_UlnarNerveRight',
    'tinels_upper_guyon\'s_canal-_ulnar_nerve_left': 'tinelsUpperGuyonsCanal_UlnarNerveLeft',
    'transverse_ligament_stability_transverse_ligament_stability': 'transverseLigamentStabilityTransverseLigamentStability'
  };

  private readonly booleanFields = new Set([
    'complaintsOfAnyRadicularSymptomsInEitherExtremity',
    'cranialNerveScreen',
    'myotomesUpper',
    'myotomesLower',
    'dermatomesUpper',
    'dermatomesLower',
    'upperReflexes',
    'lowerReflexes',
    'neuralTissueTensionUpper',
    'neuralTissueTensionLower',
    'vascular',
    'vertebralArtery',
    'allenSTestCirculation',
    'capillaryRefill',
    'homanSSign',
    'thoracicOutlet',
    'lasegueSSlr',
    'slump',
    'quadrantTesting',
    'proneKneeBendNachlas',
    'kernigBrudzinskiTest',
    'cramTest',
    'seatedDuralStretch',
    'semmesWeinsteinLower',
    'fstToeSemmesWeinsteinLower',
    'sndToeSemmesWeinsteinLower',
    'thrdToeSemmesWeinsteinLower',
    'frthToeSemmesWeinsteinLower',
    'fifthToeSemmesWeinsteinLower',
    'plantarSurfaceSemmesWeinsteinLower',
    'dorsalSurfaceSemmesWeinsteinLower',
    'semmesWeinsteinUpper',
    'thumbSemmesWeinsteinUpper',
    'indexFingerSemmesWeinsteinUpper',
    'middleFingerSemmesWeinsteinUpper',
    'ringFingerSemmesWeinsteinUpper',
    'smallFingerSemmesWeinsteinUpper',
    'tinelSLower',
    'tinelSUpper',
    'transverseLigamentStability',
    'additionalComments'
  ]);

  toModel(formValue: any): NeuroVascular {
    const model: any = {};

    for (const [formKey, dtoKey] of Object.entries(this.formToDto)) {
      if (formValue.hasOwnProperty(formKey)) {
        const value = formValue[formKey];

        if (this.booleanFields.has(dtoKey)) {
          model[dtoKey] = value === 'yes';
        } else {
          model[dtoKey] = value || '';
        }
      }
    }

    return model as NeuroVascular;
  }

  fromDto(dto: NeuroVascular): any {
    const formValue: any = {};

    for (const [formKey, dtoKey] of Object.entries(this.formToDto)) {
      if (dto.hasOwnProperty(dtoKey)) {
        const value = (dto as any)[dtoKey];

        if (this.booleanFields.has(dtoKey)) {
          formValue[formKey] = value ? 'yes' : 'no';
        } else {
          formValue[formKey] = value || '';
        }
      }
    }

    return formValue;
  }
}
